# Modelamiento estadístico

En este capítulo vamos a revisar que significa modelar.

## Modelos
Revisa este <a href="https://www.youtube.com/watch?v=DOIjIB1FGYY" target="_blank">video (17')</a> y trata de responder:

- ¿Qué es un modelo estadístico?
- ¿Por qué es importante tener buenos modelos?
- ¿Cómo de determina el error en un modelo?
- ¿Qué son los grados de libertad?

## La ecuación de la recta
Revisa este <a href="https://www.youtube.com/watch?v=In1vL_kZeYk" target="_blank">video (8')</a> y trata de responder:

- ¿Cómo se define la línea de la ecuación de un GLM que se ajuste mejor a los datos?
- ¿Cuál es el modelo más básico con el cual se compara un modelo que uno construya?

## La suma de cuadrados
Revisa este <a href="https://www.youtube.com/watch?v=maFx6TKuaQI" target="_blank">video (14')</a> y trata de responder:

- ¿Qué es la SS total?
- ¿Qué es la SS de los residuales?
- ¿Qué es la SS del modelo?
- ¿Cómo se establece que un modelo dado explica mejor los datos que un modelo básico?
- ¿Cómo se establece cuan bueno es un modelo comparado con cuan malo es? ¿Lo que explica y lo que no explica un modelo?
