<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 10 Más allá del ANOVA | Estadística con R</title>
  <meta name="description" content="Capítulo 10 Más allá del ANOVA | Estadística con R" />
  <meta name="generator" content="bookdown 0.38 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 10 Más allá del ANOVA | Estadística con R" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 10 Más allá del ANOVA | Estadística con R" />
  
  
  

<meta name="author" content="Facultad de Psicología, Universidad de Talca" />


<meta name="date" content="2024-11-24" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="después-del-anova.html"/>
<link rel="next" href="otros-análisis.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />










<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Estadística</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preámbulo</a></li>
<li class="chapter" data-level="1" data-path="introducción-a-la-estadística.html"><a href="introducción-a-la-estadística.html"><i class="fa fa-check"></i><b>1</b> Introducción a la estadística</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introducción-a-la-estadística.html"><a href="introducción-a-la-estadística.html#qué-es-la-estadística"><i class="fa fa-check"></i><b>1.1</b> ¿Qué es la estadística?</a></li>
<li class="chapter" data-level="1.2" data-path="introducción-a-la-estadística.html"><a href="introducción-a-la-estadística.html#qué-son-las-variables"><i class="fa fa-check"></i><b>1.2</b> ¿Qué son las variables?</a></li>
<li class="chapter" data-level="1.3" data-path="introducción-a-la-estadística.html"><a href="introducción-a-la-estadística.html#diseños-experimentales"><i class="fa fa-check"></i><b>1.3</b> Diseños experimentales</a></li>
<li class="chapter" data-level="1.4" data-path="introducción-a-la-estadística.html"><a href="introducción-a-la-estadística.html#qué-medir"><i class="fa fa-check"></i><b>1.4</b> ¿Qué medir?</a></li>
<li class="chapter" data-level="1.5" data-path="introducción-a-la-estadística.html"><a href="introducción-a-la-estadística.html#la-prueba-estadística"><i class="fa fa-check"></i><b>1.5</b> La prueba estadística</a></li>
<li class="chapter" data-level="1.6" data-path="introducción-a-la-estadística.html"><a href="introducción-a-la-estadística.html#que-diseño-usar"><i class="fa fa-check"></i><b>1.6</b> ¿Que diseño usar?</a></li>
<li class="chapter" data-level="1.7" data-path="introducción-a-la-estadística.html"><a href="introducción-a-la-estadística.html#el-origen-de-p"><i class="fa fa-check"></i><b>1.7</b> El origen de p</a></li>
<li class="chapter" data-level="1.8" data-path="introducción-a-la-estadística.html"><a href="introducción-a-la-estadística.html#para-qué-randomizar"><i class="fa fa-check"></i><b>1.8</b> ¿Para qué randomizar?</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="conceptos-estadísticos-claves.html"><a href="conceptos-estadísticos-claves.html"><i class="fa fa-check"></i><b>2</b> Conceptos estadísticos claves</a>
<ul>
<li class="chapter" data-level="2.1" data-path="conceptos-estadísticos-claves.html"><a href="conceptos-estadísticos-claves.html#la-significancia"><i class="fa fa-check"></i><b>2.1</b> La significancia</a></li>
<li class="chapter" data-level="2.2" data-path="conceptos-estadísticos-claves.html"><a href="conceptos-estadísticos-claves.html#las-colas"><i class="fa fa-check"></i><b>2.2</b> Las colas</a></li>
<li class="chapter" data-level="2.3" data-path="conceptos-estadísticos-claves.html"><a href="conceptos-estadísticos-claves.html#los-errores-estadísticos"><i class="fa fa-check"></i><b>2.3</b> Los errores estadísticos</a></li>
<li class="chapter" data-level="2.4" data-path="conceptos-estadísticos-claves.html"><a href="conceptos-estadísticos-claves.html#tamaño-poder"><i class="fa fa-check"></i><b>2.4</b> Tamaño &amp; poder</a></li>
<li class="chapter" data-level="2.5" data-path="conceptos-estadísticos-claves.html"><a href="conceptos-estadísticos-claves.html#cómo-planificar-un-estudio"><i class="fa fa-check"></i><b>2.5</b> ¿Cómo planificar un estudio?</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="programación.html"><a href="programación.html"><i class="fa fa-check"></i><b>3</b> Programación</a>
<ul>
<li class="chapter" data-level="3.1" data-path="programación.html"><a href="programación.html#qué-significa-programar"><i class="fa fa-check"></i><b>3.1</b> ¿Qué significa programar?</a></li>
<li class="chapter" data-level="3.2" data-path="programación.html"><a href="programación.html#la-consola-versus-el-script"><i class="fa fa-check"></i><b>3.2</b> La consola versus el script</a></li>
<li class="chapter" data-level="3.3" data-path="programación.html"><a href="programación.html#introducción-a-la-programación"><i class="fa fa-check"></i><b>3.3</b> Introducción a la programación</a></li>
<li class="chapter" data-level="3.4" data-path="programación.html"><a href="programación.html#empezar-a-programar"><i class="fa fa-check"></i><b>3.4</b> Empezar a programar</a></li>
<li class="chapter" data-level="3.5" data-path="programación.html"><a href="programación.html#trabajar-con-data-frames"><i class="fa fa-check"></i><b>3.5</b> Trabajar con data frames</a></li>
<li class="chapter" data-level="3.6" data-path="programación.html"><a href="programación.html#importar-datos"><i class="fa fa-check"></i><b>3.6</b> Importar datos</a></li>
<li class="chapter" data-level="3.7" data-path="programación.html"><a href="programación.html#seleccionar-datos"><i class="fa fa-check"></i><b>3.7</b> Seleccionar datos</a></li>
<li class="chapter" data-level="3.8" data-path="programación.html"><a href="programación.html#transformar-datos-long-vs-wide"><i class="fa fa-check"></i><b>3.8</b> Transformar datos (long vs wide)</a></li>
<li class="chapter" data-level="3.9" data-path="programación.html"><a href="programación.html#exportar-datos"><i class="fa fa-check"></i><b>3.9</b> Exportar datos</a></li>
<li class="chapter" data-level="3.10" data-path="programación.html"><a href="programación.html#en-la-práctica"><i class="fa fa-check"></i><b>3.10</b> En la práctica</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="gráficos.html"><a href="gráficos.html"><i class="fa fa-check"></i><b>4</b> Gráficos</a>
<ul>
<li class="chapter" data-level="4.1" data-path="gráficos.html"><a href="gráficos.html#cómo-graficamos-en-r"><i class="fa fa-check"></i><b>4.1</b> ¿Cómo graficamos en R?</a></li>
<li class="chapter" data-level="4.2" data-path="gráficos.html"><a href="gráficos.html#gráfico-de-puntos"><i class="fa fa-check"></i><b>4.2</b> Gráfico de puntos</a></li>
<li class="chapter" data-level="4.3" data-path="gráficos.html"><a href="gráficos.html#gráfico-de-dispersión"><i class="fa fa-check"></i><b>4.3</b> Gráfico de dispersión</a></li>
<li class="chapter" data-level="4.4" data-path="gráficos.html"><a href="gráficos.html#histograma"><i class="fa fa-check"></i><b>4.4</b> Histograma</a></li>
<li class="chapter" data-level="4.5" data-path="gráficos.html"><a href="gráficos.html#boxplot"><i class="fa fa-check"></i><b>4.5</b> Boxplot</a></li>
<li class="chapter" data-level="4.6" data-path="gráficos.html"><a href="gráficos.html#gráfico-de-barras"><i class="fa fa-check"></i><b>4.6</b> Gráfico de barras</a></li>
<li class="chapter" data-level="4.7" data-path="gráficos.html"><a href="gráficos.html#gráfico-de-líneas-1-factor"><i class="fa fa-check"></i><b>4.7</b> Gráfico de líneas (1 factor)</a></li>
<li class="chapter" data-level="4.8" data-path="gráficos.html"><a href="gráficos.html#gráfico-de-líneas-2-factores"><i class="fa fa-check"></i><b>4.8</b> Gráfico de líneas (2 factores)</a></li>
<li class="chapter" data-level="4.9" data-path="gráficos.html"><a href="gráficos.html#guardar-una-figura"><i class="fa fa-check"></i><b>4.9</b> Guardar una figura</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="caracterizar-datos.html"><a href="caracterizar-datos.html"><i class="fa fa-check"></i><b>5</b> Caracterizar datos</a>
<ul>
<li class="chapter" data-level="5.1" data-path="caracterizar-datos.html"><a href="caracterizar-datos.html#visualizar-los-datos"><i class="fa fa-check"></i><b>5.1</b> Visualizar los datos</a></li>
<li class="chapter" data-level="5.2" data-path="caracterizar-datos.html"><a href="caracterizar-datos.html#la-curva-normal"><i class="fa fa-check"></i><b>5.2</b> La curva normal</a></li>
<li class="chapter" data-level="5.3" data-path="caracterizar-datos.html"><a href="caracterizar-datos.html#la-curva-normal-en-la-práctica-1"><i class="fa fa-check"></i><b>5.3</b> La curva normal en la práctica (1)</a></li>
<li class="chapter" data-level="5.4" data-path="caracterizar-datos.html"><a href="caracterizar-datos.html#la-curva-normal-en-la-práctica-2"><i class="fa fa-check"></i><b>5.4</b> La curva normal en la práctica (2)</a></li>
<li class="chapter" data-level="5.5" data-path="caracterizar-datos.html"><a href="caracterizar-datos.html#de-la-muestra-a-la-población"><i class="fa fa-check"></i><b>5.5</b> De la muestra a la población</a></li>
<li class="chapter" data-level="5.6" data-path="caracterizar-datos.html"><a href="caracterizar-datos.html#la-muestra-en-la-vida-real"><i class="fa fa-check"></i><b>5.6</b> La muestra en la vida real</a></li>
<li class="chapter" data-level="5.7" data-path="caracterizar-datos.html"><a href="caracterizar-datos.html#los-intervalos-de-confianza-1"><i class="fa fa-check"></i><b>5.7</b> Los intervalos de confianza (1)</a></li>
<li class="chapter" data-level="5.8" data-path="caracterizar-datos.html"><a href="caracterizar-datos.html#los-intervalos-de-confianza-2"><i class="fa fa-check"></i><b>5.8</b> Los intervalos de confianza (2)</a></li>
<li class="chapter" data-level="5.9" data-path="caracterizar-datos.html"><a href="caracterizar-datos.html#verificar-supuestos"><i class="fa fa-check"></i><b>5.9</b> Verificar supuestos</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="la-regresión.html"><a href="la-regresión.html"><i class="fa fa-check"></i><b>6</b> La regresión</a>
<ul>
<li class="chapter" data-level="6.1" data-path="la-regresión.html"><a href="la-regresión.html#modelos-estadísticos"><i class="fa fa-check"></i><b>6.1</b> Modelos estadísticos</a></li>
<li class="chapter" data-level="6.2" data-path="la-regresión.html"><a href="la-regresión.html#la-ecuación-de-la-recta"><i class="fa fa-check"></i><b>6.2</b> La ecuación de la recta</a></li>
<li class="chapter" data-level="6.3" data-path="la-regresión.html"><a href="la-regresión.html#la-suma-de-cuadrados"><i class="fa fa-check"></i><b>6.3</b> La suma de cuadrados</a></li>
<li class="chapter" data-level="6.4" data-path="la-regresión.html"><a href="la-regresión.html#la-regresión-con-r"><i class="fa fa-check"></i><b>6.4</b> La regresión con R</a></li>
<li class="chapter" data-level="6.5" data-path="la-regresión.html"><a href="la-regresión.html#la-correlación-con-r"><i class="fa fa-check"></i><b>6.5</b> La correlación con R</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="la-prueba-de-t-comparar-2-grupos.html"><a href="la-prueba-de-t-comparar-2-grupos.html"><i class="fa fa-check"></i><b>7</b> La prueba de t (comparar 2 grupos)</a>
<ul>
<li class="chapter" data-level="7.1" data-path="la-prueba-de-t-comparar-2-grupos.html"><a href="la-prueba-de-t-comparar-2-grupos.html#cómo-comparamos-dos-grupos"><i class="fa fa-check"></i><b>7.1</b> ¿Cómo comparamos dos grupos?</a></li>
<li class="chapter" data-level="7.2" data-path="la-prueba-de-t-comparar-2-grupos.html"><a href="la-prueba-de-t-comparar-2-grupos.html#la-distribución-normal-de-dos-grupos"><i class="fa fa-check"></i><b>7.2</b> La distribución normal de dos grupos</a></li>
<li class="chapter" data-level="7.3" data-path="la-prueba-de-t-comparar-2-grupos.html"><a href="la-prueba-de-t-comparar-2-grupos.html#la-prueba-de-hipótesis"><i class="fa fa-check"></i><b>7.3</b> La prueba de hipótesis</a></li>
<li class="chapter" data-level="7.4" data-path="la-prueba-de-t-comparar-2-grupos.html"><a href="la-prueba-de-t-comparar-2-grupos.html#el-t-test-como-un-modelo-líneal-general"><i class="fa fa-check"></i><b>7.4</b> El t-test como un modelo líneal general</a></li>
<li class="chapter" data-level="7.5" data-path="la-prueba-de-t-comparar-2-grupos.html"><a href="la-prueba-de-t-comparar-2-grupos.html#el-t-test-con-r"><i class="fa fa-check"></i><b>7.5</b> El t-test con R</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="anova-comparar-3-grupos-o-más.html"><a href="anova-comparar-3-grupos-o-más.html"><i class="fa fa-check"></i><b>8</b> ANOVA (comparar 3 grupos o más)</a>
<ul>
<li class="chapter" data-level="8.1" data-path="anova-comparar-3-grupos-o-más.html"><a href="anova-comparar-3-grupos-o-más.html#por-qué-necesitamos-un-anova"><i class="fa fa-check"></i><b>8.1</b> ¿Por qué necesitamos un ANOVA?</a></li>
<li class="chapter" data-level="8.2" data-path="anova-comparar-3-grupos-o-más.html"><a href="anova-comparar-3-grupos-o-más.html#el-anova-como-un-modelo-líneal-general"><i class="fa fa-check"></i><b>8.2</b> El ANOVA como un modelo líneal general</a></li>
<li class="chapter" data-level="8.3" data-path="anova-comparar-3-grupos-o-más.html"><a href="anova-comparar-3-grupos-o-más.html#la-lógica-del-anova"><i class="fa fa-check"></i><b>8.3</b> La lógica del ANOVA</a></li>
<li class="chapter" data-level="8.4" data-path="anova-comparar-3-grupos-o-más.html"><a href="anova-comparar-3-grupos-o-más.html#el-anova-con-r"><i class="fa fa-check"></i><b>8.4</b> El ANOVA con R</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="después-del-anova.html"><a href="después-del-anova.html"><i class="fa fa-check"></i><b>9</b> Después del ANOVA</a>
<ul>
<li class="chapter" data-level="9.1" data-path="después-del-anova.html"><a href="después-del-anova.html#qué-hacemos-después-de-un-anova"><i class="fa fa-check"></i><b>9.1</b> ¿Qué hacemos después de un ANOVA?</a></li>
<li class="chapter" data-level="9.2" data-path="después-del-anova.html"><a href="después-del-anova.html#comparaciones-planificadas"><i class="fa fa-check"></i><b>9.2</b> Comparaciones planificadas</a></li>
<li class="chapter" data-level="9.3" data-path="después-del-anova.html"><a href="después-del-anova.html#cálculos-con-r"><i class="fa fa-check"></i><b>9.3</b> Cálculos con R</a></li>
<li class="chapter" data-level="9.4" data-path="después-del-anova.html"><a href="después-del-anova.html#pruebas-post-hoc"><i class="fa fa-check"></i><b>9.4</b> Pruebas post-hoc</a></li>
<li class="chapter" data-level="9.5" data-path="después-del-anova.html"><a href="después-del-anova.html#cálculos-con-r-1"><i class="fa fa-check"></i><b>9.5</b> Cálculos con R</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="más-allá-del-anova.html"><a href="más-allá-del-anova.html"><i class="fa fa-check"></i><b>10</b> Más allá del ANOVA</a>
<ul>
<li class="chapter" data-level="10.1" data-path="más-allá-del-anova.html"><a href="más-allá-del-anova.html#tipos-de-anova"><i class="fa fa-check"></i><b>10.1</b> Tipos de ANOVA</a></li>
<li class="chapter" data-level="10.2" data-path="más-allá-del-anova.html"><a href="más-allá-del-anova.html#anova-factorial"><i class="fa fa-check"></i><b>10.2</b> ANOVA factorial</a></li>
<li class="chapter" data-level="10.3" data-path="más-allá-del-anova.html"><a href="más-allá-del-anova.html#anova-de-medidas-repetidas"><i class="fa fa-check"></i><b>10.3</b> ANOVA de medidas repetidas</a></li>
<li class="chapter" data-level="10.4" data-path="más-allá-del-anova.html"><a href="más-allá-del-anova.html#ancova"><i class="fa fa-check"></i><b>10.4</b> ANCOVA</a></li>
<li class="chapter" data-level="10.5" data-path="más-allá-del-anova.html"><a href="más-allá-del-anova.html#manova"><i class="fa fa-check"></i><b>10.5</b> MANOVA</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="otros-análisis.html"><a href="otros-análisis.html"><i class="fa fa-check"></i><b>11</b> Otros análisis</a>
<ul>
<li class="chapter" data-level="11.1" data-path="otros-análisis.html"><a href="otros-análisis.html#análisis-de-proporciones"><i class="fa fa-check"></i><b>11.1</b> Análisis de proporciones</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="recursos.html"><a href="recursos.html"><i class="fa fa-check"></i><b>12</b> Recursos</a>
<ul>
<li class="chapter" data-level="12.1" data-path="recursos.html"><a href="recursos.html#apps"><i class="fa fa-check"></i><b>12.1</b> Apps</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="recursos.html"><a href="recursos.html#convertidor-de-tamaños-de-efectos"><i class="fa fa-check"></i><b>12.1.1</b> Convertidor de tamaños de efectos</a></li>
<li class="chapter" data-level="12.1.2" data-path="recursos.html"><a href="recursos.html#convertidor-de-tamaños-de-efectos-1"><i class="fa fa-check"></i><b>12.1.2</b> Convertidor de tamaños de efectos</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="recursos.html"><a href="recursos.html#librerías"><i class="fa fa-check"></i><b>12.2</b> Librerías</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="recursos.html"><a href="recursos.html#para-calcular-tamaños-de-efectos"><i class="fa fa-check"></i><b>12.2.1</b> Para calcular tamaños de efectos</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="recursos.html"><a href="recursos.html#sitios-web"><i class="fa fa-check"></i><b>12.3</b> Sitios web</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="recursos.html"><a href="recursos.html#herramientas-de-estadística"><i class="fa fa-check"></i><b>12.3.1</b> Herramientas de estadística</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="recursos.html"><a href="recursos.html#cursos"><i class="fa fa-check"></i><b>12.4</b> Cursos</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="recursos.html"><a href="recursos.html#herramientas-de-estadística-1"><i class="fa fa-check"></i><b>12.4.1</b> Herramientas de estadística</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Estadística con R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="más-allá-del-anova" class="section level1" number="10">
<h1><span class="header-section-number">Capítulo 10</span> Más allá del ANOVA</h1>
<p>En este capítulo vamos a revisar que otros tipos de ANOVA podemos realizar.</p>
<div id="tipos-de-anova" class="section level2" number="10.1">
<h2><span class="header-section-number">10.1</span> Tipos de ANOVA</h2>
<p>Revisa este <a href="https://www.youtube.com/watch?v=ha_fahDpbSg" target="_blank">video (13’)</a> y trata de responder:</p>
<ul>
<li>¿De qué depende el tipo de ANOVA que utilicemos?</li>
</ul>
</div>
<div id="anova-factorial" class="section level2" number="10.2">
<h2><span class="header-section-number">10.2</span> ANOVA factorial</h2>
<p>Ahora vamos a hacer un análisis de ANOVA factorial. Primero seteamos nuestro directorio de trabajo y cargamos las librerías que necesitemos (si no las tienes instaladas debes instalarlas).</p>
<div class="sourceCode" id="cb436"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb436-1"><a href="más-allá-del-anova.html#cb436-1" tabindex="-1"></a><span class="fu">setwd</span>(<span class="fu">Sys.getenv</span>(<span class="st">&quot;BOOKDOWN_PROJECT_PATH&quot;</span>))</span>
<span id="cb436-2"><a href="más-allá-del-anova.html#cb436-2" tabindex="-1"></a></span>
<span id="cb436-3"><a href="más-allá-del-anova.html#cb436-3" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb436-4"><a href="más-allá-del-anova.html#cb436-4" tabindex="-1"></a><span class="fu">library</span>(Hmisc)</span>
<span id="cb436-5"><a href="más-allá-del-anova.html#cb436-5" tabindex="-1"></a><span class="fu">library</span>(Rmisc)</span>
<span id="cb436-6"><a href="más-allá-del-anova.html#cb436-6" tabindex="-1"></a><span class="fu">library</span>(effsize)</span>
<span id="cb436-7"><a href="más-allá-del-anova.html#cb436-7" tabindex="-1"></a><span class="fu">library</span>(pastecs)</span>
<span id="cb436-8"><a href="más-allá-del-anova.html#cb436-8" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span>
<span id="cb436-9"><a href="más-allá-del-anova.html#cb436-9" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb436-10"><a href="más-allá-del-anova.html#cb436-10" tabindex="-1"></a><span class="fu">library</span>(effsize)</span></code></pre></div>
<p>Primero importamos el set de datos y le damos una mirada.</p>
<div class="sourceCode" id="cb437"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb437-1"><a href="más-allá-del-anova.html#cb437-1" tabindex="-1"></a>gogglesData <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/goggle_beer_effect.csv&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb437-2"><a href="más-allá-del-anova.html#cb437-2" tabindex="-1"></a><span class="fu">head</span>(gogglesData)</span></code></pre></div>
<pre><code>##   gender alcohol attractiveness
## 1 Female    None             65
## 2 Female    None             70
## 3 Female    None             60
## 4 Female    None             60
## 5 Female    None             60
## 6 Female    None             55</code></pre>
<p>Enseguida es útil decirle a R que variables corresponden a factores.</p>
<div class="sourceCode" id="cb439"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb439-1"><a href="más-allá-del-anova.html#cb439-1" tabindex="-1"></a>gogglesData<span class="sc">$</span>gender <span class="ot">&lt;-</span> <span class="fu">factor</span>(gogglesData<span class="sc">$</span>gender)</span>
<span id="cb439-2"><a href="más-allá-del-anova.html#cb439-2" tabindex="-1"></a>gogglesData<span class="sc">$</span>alcohol <span class="ot">&lt;-</span> <span class="fu">factor</span>(gogglesData<span class="sc">$</span>alcohol)</span>
<span id="cb439-3"><a href="más-allá-del-anova.html#cb439-3" tabindex="-1"></a></span>
<span id="cb439-4"><a href="más-allá-del-anova.html#cb439-4" tabindex="-1"></a><span class="fu">str</span>(gogglesData)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    48 obs. of  3 variables:
##  $ gender        : Factor w/ 2 levels &quot;Female&quot;,&quot;Male&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ alcohol       : Factor w/ 3 levels &quot;2 Pints&quot;,&quot;4 Pints&quot;,..: 3 3 3 3 3 3 3 3 1 1 ...
##  $ attractiveness: int  65 70 60 60 60 55 60 55 70 65 ...</code></pre>
<p>También podemos cambiar el nombre de las variables si nos facilita la tarea de hacer gráficos por ejemplo.</p>
<div class="sourceCode" id="cb441"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb441-1"><a href="más-allá-del-anova.html#cb441-1" tabindex="-1"></a><span class="fu">levels</span>(gogglesData<span class="sc">$</span>alcohol)[<span class="fu">match</span>(<span class="st">&quot;None&quot;</span>, <span class="fu">levels</span>(gogglesData<span class="sc">$</span>alcohol))] <span class="ot">&lt;-</span> <span class="st">&quot;P0&quot;</span></span>
<span id="cb441-2"><a href="más-allá-del-anova.html#cb441-2" tabindex="-1"></a><span class="fu">levels</span>(gogglesData<span class="sc">$</span>alcohol)[<span class="fu">match</span>(<span class="st">&quot;2 Pints&quot;</span>, <span class="fu">levels</span>(gogglesData<span class="sc">$</span>alcohol))] <span class="ot">&lt;-</span> <span class="st">&quot;P2&quot;</span></span>
<span id="cb441-3"><a href="más-allá-del-anova.html#cb441-3" tabindex="-1"></a><span class="fu">levels</span>(gogglesData<span class="sc">$</span>alcohol)[<span class="fu">match</span>(<span class="st">&quot;4 Pints&quot;</span>, <span class="fu">levels</span>(gogglesData<span class="sc">$</span>alcohol))] <span class="ot">&lt;-</span> <span class="st">&quot;P4&quot;</span></span>
<span id="cb441-4"><a href="más-allá-del-anova.html#cb441-4" tabindex="-1"></a></span>
<span id="cb441-5"><a href="más-allá-del-anova.html#cb441-5" tabindex="-1"></a><span class="fu">str</span>(gogglesData)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    48 obs. of  3 variables:
##  $ gender        : Factor w/ 2 levels &quot;Female&quot;,&quot;Male&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ alcohol       : Factor w/ 3 levels &quot;P2&quot;,&quot;P4&quot;,&quot;P0&quot;: 3 3 3 3 3 3 3 3 1 1 ...
##  $ attractiveness: int  65 70 60 60 60 55 60 55 70 65 ...</code></pre>
<p>Fíjate que el nivel base quedó al final.</p>
<div class="sourceCode" id="cb443"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb443-1"><a href="más-allá-del-anova.html#cb443-1" tabindex="-1"></a><span class="fu">levels</span>(gogglesData<span class="sc">$</span>alcohol)</span></code></pre></div>
<pre><code>## [1] &quot;P2&quot; &quot;P4&quot; &quot;P0&quot;</code></pre>
<p>Necesitamos reordenar los niveles para este factor.</p>
<div class="sourceCode" id="cb445"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb445-1"><a href="más-allá-del-anova.html#cb445-1" tabindex="-1"></a>gogglesData<span class="sc">$</span>alcohol <span class="ot">&lt;-</span> <span class="fu">factor</span>(gogglesData<span class="sc">$</span>alcohol,</span>
<span id="cb445-2"><a href="más-allá-del-anova.html#cb445-2" tabindex="-1"></a>                              <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;P0&quot;</span>, <span class="st">&quot;P2&quot;</span>, <span class="st">&quot;P4&quot;</span>))</span>
<span id="cb445-3"><a href="más-allá-del-anova.html#cb445-3" tabindex="-1"></a><span class="fu">levels</span>(gogglesData<span class="sc">$</span>alcohol)</span></code></pre></div>
<pre><code>## [1] &quot;P0&quot; &quot;P2&quot; &quot;P4&quot;</code></pre>
<p>Luego, podemos hacer algunos gráficos para visualizar los efectos.
Por ejemplo, podemos hacer un histograma de los valores de atractivo en función del género y del consumo de alcohol.</p>
<div class="sourceCode" id="cb447"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb447-1"><a href="más-allá-del-anova.html#cb447-1" tabindex="-1"></a>fig_boxplot1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(gogglesData, <span class="fu">aes</span>(alcohol, attractiveness)) <span class="sc">+</span></span>
<span id="cb447-2"><a href="más-allá-del-anova.html#cb447-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> </span>
<span id="cb447-3"><a href="más-allá-del-anova.html#cb447-3" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>gender) <span class="sc">+</span> </span>
<span id="cb447-4"><a href="más-allá-del-anova.html#cb447-4" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Consumo de alcohol&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Atractivo promedio (%)&quot;</span>) <span class="sc">+</span></span>
<span id="cb447-5"><a href="más-allá-del-anova.html#cb447-5" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(), </span>
<span id="cb447-6"><a href="más-allá-del-anova.html#cb447-6" tabindex="-1"></a>        <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb447-7"><a href="más-allá-del-anova.html#cb447-7" tabindex="-1"></a>        <span class="at">panel.background =</span> <span class="fu">element_blank</span>(), </span>
<span id="cb447-8"><a href="más-allá-del-anova.html#cb447-8" tabindex="-1"></a>        <span class="at">axis.line =</span> <span class="fu">element_line</span>(<span class="at">colour =</span> <span class="st">&quot;black&quot;</span>))</span>
<span id="cb447-9"><a href="más-allá-del-anova.html#cb447-9" tabindex="-1"></a>fig_boxplot1</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-217-1.png" width="672" /></p>
<p>Este mismo gráfico, valores de atractivo en función del género y del consumo de alcohol, se puede hacer en formato de líneas.</p>
<div class="sourceCode" id="cb448"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb448-1"><a href="más-allá-del-anova.html#cb448-1" tabindex="-1"></a>fig_linesplot1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(gogglesData, <span class="fu">aes</span>(alcohol, attractiveness, <span class="at">colour =</span> gender)) <span class="sc">+</span></span>
<span id="cb448-2"><a href="más-allá-del-anova.html#cb448-2" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.y =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>) <span class="sc">+</span></span>
<span id="cb448-3"><a href="más-allá-del-anova.html#cb448-3" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.y =</span> mean, <span class="at">geom =</span> <span class="st">&quot;line&quot;</span>, <span class="fu">aes</span>(<span class="at">group=</span> gender)) <span class="sc">+</span></span>
<span id="cb448-4"><a href="más-allá-del-anova.html#cb448-4" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_cl_boot, <span class="at">geom =</span> <span class="st">&quot;errorbar&quot;</span>, <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb448-5"><a href="más-allá-del-anova.html#cb448-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Consumo de alcohol&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Atractivo promedio (%)&quot;</span>, <span class="at">colour =</span> <span class="st">&quot;Gender&quot;</span>) <span class="sc">+</span></span>
<span id="cb448-6"><a href="más-allá-del-anova.html#cb448-6" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(), </span>
<span id="cb448-7"><a href="más-allá-del-anova.html#cb448-7" tabindex="-1"></a>        <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb448-8"><a href="más-allá-del-anova.html#cb448-8" tabindex="-1"></a>        <span class="at">panel.background =</span> <span class="fu">element_blank</span>(), </span>
<span id="cb448-9"><a href="más-allá-del-anova.html#cb448-9" tabindex="-1"></a>        <span class="at">axis.line =</span> <span class="fu">element_line</span>(<span class="at">colour =</span> <span class="st">&quot;black&quot;</span>))</span>
<span id="cb448-10"><a href="más-allá-del-anova.html#cb448-10" tabindex="-1"></a>fig_linesplot1</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-218-1.png" width="672" /></p>
<p>O en formato de barras.</p>
<div class="sourceCode" id="cb449"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb449-1"><a href="más-allá-del-anova.html#cb449-1" tabindex="-1"></a>fig_barplot1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(gogglesData, <span class="fu">aes</span>(alcohol, attractiveness, <span class="at">fill =</span> gender)) <span class="sc">+</span></span>
<span id="cb449-2"><a href="más-allá-del-anova.html#cb449-2" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_cl_normal, <span class="at">geom =</span> <span class="st">&quot;errorbar&quot;</span>,</span>
<span id="cb449-3"><a href="más-allá-del-anova.html#cb449-3" tabindex="-1"></a>               <span class="at">position=</span><span class="fu">position_dodge</span>(<span class="at">width=</span><span class="fl">0.90</span>), <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb449-4"><a href="más-allá-del-anova.html#cb449-4" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.y =</span> mean, <span class="at">geom =</span> <span class="st">&quot;bar&quot;</span>, <span class="at">position=</span><span class="st">&quot;dodge&quot;</span>) <span class="sc">+</span></span>
<span id="cb449-5"><a href="más-allá-del-anova.html#cb449-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Consumo de alcohol&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Atractivo promedio (%)&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;Gender&quot;</span>) <span class="sc">+</span>  <span class="fu">theme</span>(<span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(), </span>
<span id="cb449-6"><a href="más-allá-del-anova.html#cb449-6" tabindex="-1"></a>        <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb449-7"><a href="más-allá-del-anova.html#cb449-7" tabindex="-1"></a>        <span class="at">panel.background =</span> <span class="fu">element_blank</span>(), </span>
<span id="cb449-8"><a href="más-allá-del-anova.html#cb449-8" tabindex="-1"></a>        <span class="at">axis.line =</span> <span class="fu">element_line</span>(<span class="at">colour =</span> <span class="st">&quot;black&quot;</span>))</span>
<span id="cb449-9"><a href="más-allá-del-anova.html#cb449-9" tabindex="-1"></a>fig_barplot1</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-219-1.png" width="672" /></p>
<p>Estos gráfico son muy informativos. ¿Que ves?
Una manera de visualizar los efectos que estamos estudiando podemos separar los efectos. Esto es, podemos visualizar los niveles de atractivo en función de un sólo factor.</p>
<p>Por ejemplo, podemos visualizar el efecto del género en los niveles de atractivo.
Este efecto corresponde al <em>efecto principal</em> del género.</p>
<div class="sourceCode" id="cb450"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb450-1"><a href="más-allá-del-anova.html#cb450-1" tabindex="-1"></a>fig_bargender1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(gogglesData, <span class="fu">aes</span>(gender, attractiveness)) <span class="sc">+</span></span>
<span id="cb450-2"><a href="más-allá-del-anova.html#cb450-2" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.y =</span> mean, <span class="at">geom =</span> <span class="st">&quot;bar&quot;</span>, </span>
<span id="cb450-3"><a href="más-allá-del-anova.html#cb450-3" tabindex="-1"></a>               <span class="at">fill =</span> <span class="st">&quot;White&quot;</span>, <span class="at">colour =</span> <span class="st">&quot;Black&quot;</span>) <span class="sc">+</span></span>
<span id="cb450-4"><a href="más-allá-del-anova.html#cb450-4" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_cl_normal, <span class="at">geom =</span> <span class="st">&quot;pointrange&quot;</span>) <span class="sc">+</span></span>
<span id="cb450-5"><a href="más-allá-del-anova.html#cb450-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Género&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Atractivo promedio (%)&quot;</span>) <span class="sc">+</span></span>
<span id="cb450-6"><a href="más-allá-del-anova.html#cb450-6" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks=</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">80</span>, <span class="at">by =</span> <span class="dv">10</span>)) <span class="sc">+</span></span>
<span id="cb450-7"><a href="más-allá-del-anova.html#cb450-7" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(), </span>
<span id="cb450-8"><a href="más-allá-del-anova.html#cb450-8" tabindex="-1"></a>        <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb450-9"><a href="más-allá-del-anova.html#cb450-9" tabindex="-1"></a>        <span class="at">panel.background =</span> <span class="fu">element_blank</span>(), </span>
<span id="cb450-10"><a href="más-allá-del-anova.html#cb450-10" tabindex="-1"></a>        <span class="at">axis.line =</span> <span class="fu">element_line</span>(<span class="at">colour =</span> <span class="st">&quot;black&quot;</span>))</span>
<span id="cb450-11"><a href="más-allá-del-anova.html#cb450-11" tabindex="-1"></a>fig_bargender1</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-220-1.png" width="672" /></p>
<p>También podemos visualizar el efecto del consumo de alcohol en los niveles de atractivo.
Este efecto corresponde al <em>efecto principal</em> del consumo de alcohol.</p>
<div class="sourceCode" id="cb451"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb451-1"><a href="más-allá-del-anova.html#cb451-1" tabindex="-1"></a>fig_barbeer1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(gogglesData, <span class="fu">aes</span>(alcohol, attractiveness)) <span class="sc">+</span></span>
<span id="cb451-2"><a href="más-allá-del-anova.html#cb451-2" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.y =</span> mean, <span class="at">geom =</span> <span class="st">&quot;bar&quot;</span>, </span>
<span id="cb451-3"><a href="más-allá-del-anova.html#cb451-3" tabindex="-1"></a>                   <span class="at">fill =</span> <span class="st">&quot;White&quot;</span>, <span class="at">colour =</span> <span class="st">&quot;Black&quot;</span>) <span class="sc">+</span></span>
<span id="cb451-4"><a href="más-allá-del-anova.html#cb451-4" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_cl_normal, <span class="at">geom =</span> <span class="st">&quot;pointrange&quot;</span>) <span class="sc">+</span></span>
<span id="cb451-5"><a href="más-allá-del-anova.html#cb451-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Consumo de alcohol&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Atractivo promedio (%)&quot;</span>) <span class="sc">+</span></span>
<span id="cb451-6"><a href="más-allá-del-anova.html#cb451-6" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks=</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">80</span>, <span class="at">by =</span> <span class="dv">10</span>)) <span class="sc">+</span></span>
<span id="cb451-7"><a href="más-allá-del-anova.html#cb451-7" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(), </span>
<span id="cb451-8"><a href="más-allá-del-anova.html#cb451-8" tabindex="-1"></a>        <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb451-9"><a href="más-allá-del-anova.html#cb451-9" tabindex="-1"></a>        <span class="at">panel.background =</span> <span class="fu">element_blank</span>(), </span>
<span id="cb451-10"><a href="más-allá-del-anova.html#cb451-10" tabindex="-1"></a>        <span class="at">axis.line =</span> <span class="fu">element_line</span>(<span class="at">colour =</span> <span class="st">&quot;black&quot;</span>))</span>
<span id="cb451-11"><a href="más-allá-del-anova.html#cb451-11" tabindex="-1"></a>fig_barbeer1</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-221-1.png" width="672" /></p>
<p>Antes de hacer los análisis propiamente tal podemos describir un poco los datos y evaluar los supuestos de la estadística parámetrica.</p>
<div class="sourceCode" id="cb452"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb452-1"><a href="más-allá-del-anova.html#cb452-1" tabindex="-1"></a>describ <span class="ot">&lt;-</span> <span class="fu">by</span>(gogglesData<span class="sc">$</span>attractiveness, </span>
<span id="cb452-2"><a href="más-allá-del-anova.html#cb452-2" tabindex="-1"></a>   gogglesData<span class="sc">$</span>gender, stat.desc)</span>
<span id="cb452-3"><a href="más-allá-del-anova.html#cb452-3" tabindex="-1"></a><span class="fu">lapply</span>(describ, round, <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## $Female
##      nbr.val     nbr.null       nbr.na          min          max        range          sum       median         mean 
##        24.00         0.00         0.00        50.00        70.00        20.00      1445.00        60.00        60.21 
##      SE.mean CI.mean.0.95          var      std.dev     coef.var 
##         1.29         2.68        40.17         6.34         0.11 
## 
## $Male
##      nbr.val     nbr.null       nbr.na          min          max        range          sum       median         mean 
##        24.00         0.00         0.00        20.00        85.00        65.00      1355.00        60.00        56.46 
##      SE.mean CI.mean.0.95          var      std.dev     coef.var 
##         3.78         7.81       342.35        18.50         0.33</code></pre>
<div class="sourceCode" id="cb454"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb454-1"><a href="más-allá-del-anova.html#cb454-1" tabindex="-1"></a>describ <span class="ot">&lt;-</span> <span class="fu">by</span>(gogglesData<span class="sc">$</span>attractiveness, </span>
<span id="cb454-2"><a href="más-allá-del-anova.html#cb454-2" tabindex="-1"></a>              gogglesData<span class="sc">$</span>alcohol, stat.desc)</span>
<span id="cb454-3"><a href="más-allá-del-anova.html#cb454-3" tabindex="-1"></a><span class="fu">lapply</span>(describ, round, <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## $P0
##      nbr.val     nbr.null       nbr.na          min          max        range          sum       median         mean 
##        16.00         0.00         0.00        50.00        80.00        30.00      1020.00        62.50        63.75 
##      SE.mean CI.mean.0.95          var      std.dev     coef.var 
##         2.12         4.51        71.67         8.47         0.13 
## 
## $P2
##      nbr.val     nbr.null       nbr.na          min          max        range          sum       median         mean 
##        16.00         0.00         0.00        45.00        85.00        40.00      1035.00        65.00        64.69 
##      SE.mean CI.mean.0.95          var      std.dev     coef.var 
##         2.48         5.28        98.23         9.91         0.15 
## 
## $P4
##      nbr.val     nbr.null       nbr.na          min          max        range          sum       median         mean 
##        16.00         0.00         0.00        20.00        70.00        50.00       745.00        50.00        46.56 
##      SE.mean CI.mean.0.95          var      std.dev     coef.var 
##         3.59         7.64       205.73        14.34         0.31</code></pre>
<div class="sourceCode" id="cb456"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb456-1"><a href="más-allá-del-anova.html#cb456-1" tabindex="-1"></a>describ <span class="ot">&lt;-</span> <span class="fu">by</span>(gogglesData<span class="sc">$</span>attractiveness, </span>
<span id="cb456-2"><a href="más-allá-del-anova.html#cb456-2" tabindex="-1"></a>              <span class="fu">list</span>(gogglesData<span class="sc">$</span>alcohol, gogglesData<span class="sc">$</span>gender), </span>
<span id="cb456-3"><a href="más-allá-del-anova.html#cb456-3" tabindex="-1"></a>              stat.desc, <span class="at">basic =</span> <span class="cn">FALSE</span>)</span>
<span id="cb456-4"><a href="más-allá-del-anova.html#cb456-4" tabindex="-1"></a><span class="fu">lapply</span>(describ, round, <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [[1]]
##       median         mean      SE.mean CI.mean.0.95          var      std.dev     coef.var 
##        60.00        60.62         1.75         4.14        24.55         4.96         0.08 
## 
## [[2]]
##       median         mean      SE.mean CI.mean.0.95          var      std.dev     coef.var 
##        62.50        62.50         2.31         5.47        42.86         6.55         0.10 
## 
## [[3]]
##       median         mean      SE.mean CI.mean.0.95          var      std.dev     coef.var 
##        55.00        57.50         2.50         5.91        50.00         7.07         0.12 
## 
## [[4]]
##       median         mean      SE.mean CI.mean.0.95          var      std.dev     coef.var 
##        67.50        66.88         3.65         8.64       106.70        10.33         0.15 
## 
## [[5]]
##       median         mean      SE.mean CI.mean.0.95          var      std.dev     coef.var 
##        67.50        66.88         4.43        10.47       156.70        12.52         0.19 
## 
## [[6]]
##       median         mean      SE.mean CI.mean.0.95          var      std.dev     coef.var 
##        32.50        35.62         3.83         9.06       117.41        10.84         0.30</code></pre>
<p>También podemos evaluar la homogenididad de varianza.</p>
<div class="sourceCode" id="cb458"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb458-1"><a href="más-allá-del-anova.html#cb458-1" tabindex="-1"></a><span class="fu">leveneTest</span>(gogglesData<span class="sc">$</span>attractiveness, </span>
<span id="cb458-2"><a href="más-allá-del-anova.html#cb458-2" tabindex="-1"></a>           gogglesData<span class="sc">$</span>gender, <span class="at">center =</span> median)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value   Pr(&gt;F)    
## group  1  19.979 5.08e-05 ***
##       46                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb460"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb460-1"><a href="más-allá-del-anova.html#cb460-1" tabindex="-1"></a><span class="fu">leveneTest</span>(gogglesData<span class="sc">$</span>attractiveness, </span>
<span id="cb460-2"><a href="más-allá-del-anova.html#cb460-2" tabindex="-1"></a>           gogglesData<span class="sc">$</span>alcohol, <span class="at">center =</span> median)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  2  2.3238 0.1095
##       45</code></pre>
<div class="sourceCode" id="cb462"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb462-1"><a href="más-allá-del-anova.html#cb462-1" tabindex="-1"></a><span class="fu">leveneTest</span>(gogglesData<span class="sc">$</span>attractiveness, </span>
<span id="cb462-2"><a href="más-allá-del-anova.html#cb462-2" tabindex="-1"></a>           <span class="fu">interaction</span>(gogglesData<span class="sc">$</span>alcohol, gogglesData<span class="sc">$</span>gender),</span>
<span id="cb462-3"><a href="más-allá-del-anova.html#cb462-3" tabindex="-1"></a>           <span class="at">center =</span> median)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  5  1.4252 0.2351
##       42</code></pre>
<p>Antes de hacer el análisis de ANOVA podemos aprovechar de setear las comparaciones planificadas.
¿Para un diseño de este tipo que comparaciones harías?</p>
<p>Una posibilidad es evaluar el efecto del género. Es decir, comparar hombres versus mujeres.
Para hacer esto usamos un dummy coding muy simple. ¿Por qué simple? Porque simplemente comparas uno contra el otro. Fijate en el orden de los niveles en cada factor.</p>
<div class="sourceCode" id="cb464"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb464-1"><a href="más-allá-del-anova.html#cb464-1" tabindex="-1"></a><span class="fu">levels</span>(gogglesData<span class="sc">$</span>gender)</span></code></pre></div>
<pre><code>## [1] &quot;Female&quot; &quot;Male&quot;</code></pre>
<p>Entonces, puedes crear el siguiente constraste</p>
<div class="sourceCode" id="cb466"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb466-1"><a href="más-allá-del-anova.html#cb466-1" tabindex="-1"></a>.M_vs_F <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb466-2"><a href="más-allá-del-anova.html#cb466-2" tabindex="-1"></a>.M_vs_F</span></code></pre></div>
<pre><code>## [1] -1  1</code></pre>
<p>Otra posibilidad es evaluar el efecto del consumo de alcohol. Es decir, comparar agua versus pint versus 2 pints.Para hacer esto usamos otro dummy coding. Para hacer estos de nuevo nos fijamos en el orden de los niveles en cada factor.</p>
<div class="sourceCode" id="cb468"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb468-1"><a href="más-allá-del-anova.html#cb468-1" tabindex="-1"></a><span class="fu">levels</span>(gogglesData<span class="sc">$</span>alcohol)</span></code></pre></div>
<pre><code>## [1] &quot;P0&quot; &quot;P2&quot; &quot;P4&quot;</code></pre>
<p>¿Que efectos podríamos querer ver? Por ejemplo, el efecto de ingerir alcohol.</p>
<div class="sourceCode" id="cb470"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb470-1"><a href="más-allá-del-anova.html#cb470-1" tabindex="-1"></a>.Non_vs_P <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb470-2"><a href="más-allá-del-anova.html#cb470-2" tabindex="-1"></a>.Non_vs_P</span></code></pre></div>
<pre><code>## [1] -2  1  1</code></pre>
<p>Otro efecto que podemos estudiar es la diferencia producidad por 1 pint versus 2 pints.</p>
<div class="sourceCode" id="cb472"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb472-1"><a href="más-allá-del-anova.html#cb472-1" tabindex="-1"></a>.P2_vs_P4 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb472-2"><a href="más-allá-del-anova.html#cb472-2" tabindex="-1"></a>.P2_vs_P4</span></code></pre></div>
<pre><code>## [1]  0 -1  1</code></pre>
<p>Una vez que creamos los contraste lo ponemos en un vector.</p>
<div class="sourceCode" id="cb474"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb474-1"><a href="más-allá-del-anova.html#cb474-1" tabindex="-1"></a><span class="fu">contrasts</span>(gogglesData<span class="sc">$</span>alcohol) <span class="ot">&lt;-</span> <span class="fu">cbind</span>(.Non_vs_P, .P2_vs_P4)</span>
<span id="cb474-2"><a href="más-allá-del-anova.html#cb474-2" tabindex="-1"></a><span class="fu">contrasts</span>(gogglesData<span class="sc">$</span>gender) <span class="ot">&lt;-</span> <span class="fu">cbind</span>(.M_vs_F)</span></code></pre></div>
<p>Y los inyectamos en las bases de datos.</p>
<div class="sourceCode" id="cb475"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb475-1"><a href="más-allá-del-anova.html#cb475-1" tabindex="-1"></a><span class="fu">contrasts</span>(gogglesData<span class="sc">$</span>alcohol) <span class="ot">&lt;-</span> <span class="fu">cbind</span>(.Non_vs_P, .P2_vs_P4)</span>
<span id="cb475-2"><a href="más-allá-del-anova.html#cb475-2" tabindex="-1"></a><span class="fu">contrasts</span>(gogglesData<span class="sc">$</span>gender) <span class="ot">&lt;-</span> <span class="fu">cbind</span>(.M_vs_F)</span></code></pre></div>
<p>Luego puedes verificar para el factor género, y …</p>
<div class="sourceCode" id="cb476"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb476-1"><a href="más-allá-del-anova.html#cb476-1" tabindex="-1"></a>gogglesData<span class="sc">$</span>gender</span></code></pre></div>
<pre><code>##  [1] Female Female Female Female Female Female Female Female Female Female Female Female Female Female Female Female Female
## [18] Female Female Female Female Female Female Female Male   Male   Male   Male   Male   Male   Male   Male   Male   Male  
## [35] Male   Male   Male   Male   Male   Male   Male   Male   Male   Male   Male   Male   Male   Male  
## attr(,&quot;contrasts&quot;)
##        .M_vs_F
## Female      -1
## Male         1
## Levels: Female Male</code></pre>
<p>… consumo de alcohol</p>
<div class="sourceCode" id="cb478"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb478-1"><a href="más-allá-del-anova.html#cb478-1" tabindex="-1"></a>gogglesData<span class="sc">$</span>alcohol</span></code></pre></div>
<pre><code>##  [1] P0 P0 P0 P0 P0 P0 P0 P0 P2 P2 P2 P2 P2 P2 P2 P2 P4 P4 P4 P4 P4 P4 P4 P4 P0 P0 P0 P0 P0 P0 P0 P0 P2 P2 P2 P2 P2 P2 P2 P2 P4
## [42] P4 P4 P4 P4 P4 P4 P4
## attr(,&quot;contrasts&quot;)
##    .Non_vs_P .P2_vs_P4
## P0        -2         0
## P2         1        -1
## P4         1         1
## Levels: P0 P2 P4</code></pre>
<p>Una vez que hemos seteado nuestros contrastes podemos hacer el modelo y visualizar los resultados.
En el modelo tratamos de predecir los valores de atractivo en base al género, el consumo de alcohol y la interacción entre ambos factores. Para ello se usa un simbolo (*) que indica que queremos analizar los efectos principales y el efecto de interacción.</p>
<div class="sourceCode" id="cb480"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb480-1"><a href="más-allá-del-anova.html#cb480-1" tabindex="-1"></a>gogglesModel <span class="ot">&lt;-</span> <span class="fu">aov</span>(attractiveness <span class="sc">~</span> gender<span class="sc">*</span>alcohol, gogglesData)</span>
<span id="cb480-2"><a href="más-allá-del-anova.html#cb480-2" tabindex="-1"></a><span class="fu">Anova</span>(gogglesModel, <span class="at">type=</span><span class="st">&quot;III&quot;</span>)</span></code></pre></div>
<pre><code>## Anova Table (Type III tests)
## 
## Response: attractiveness
##                Sum Sq Df   F value    Pr(&gt;F)    
## (Intercept)    163333  1 1967.0251 &lt; 2.2e-16 ***
## gender            169  1    2.0323    0.1614    
## alcohol          3332  2   20.0654 7.649e-07 ***
## gender:alcohol   1978  2   11.9113 7.987e-05 ***
## Residuals        3488 42                        
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Si miras los valores de F verás que hay un efecto principal del alcohol y un efecto de interacción género-consumo de alcohol. El efecto principal que tenemos aquí refleja que hay un efecto del alcohol (mira el gráfico). Pero, fíjate que el efecto del alcohol en realidad esta calificado por una interación con el género. Es decir, el efecto del consumo de alcohol sobre los niveles de atractivo no son iguales para los dos géneros. En otras palabras. A la luz de una interacción no tiene sentido interpretar el efecto principal.</p>
<p>¿Qué indican los resultados? Ten en cuenta los resultados estadísticos y el gráfico.</p>
<div class="sourceCode" id="cb482"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb482-1"><a href="más-allá-del-anova.html#cb482-1" tabindex="-1"></a>fig_linesplot1</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-238-1.png" width="672" /></p>
<p>Los resultados muestran que las mujeres mantienen altos estándares en la selección de su pareja sin importar el consumo de alcohol. Los hombres toman 4 pints y terminan con parejas que tienen un menor atractivo. Es decir, ocurre el “goggle bear effect”.</p>
<p>Veamos las comparaciones planificadas para revisar mayores detalles.</p>
<div class="sourceCode" id="cb483"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb483-1"><a href="más-allá-del-anova.html#cb483-1" tabindex="-1"></a><span class="fu">summary.lm</span>(gogglesModel)</span></code></pre></div>
<pre><code>## 
## Call:
## aov(formula = attractiveness ~ gender * alcohol, data = gogglesData)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -21.875  -5.625  -0.625   5.156  19.375 
## 
## Coefficients:
##                                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                      58.333      1.315  44.351  &lt; 2e-16 ***
## gender.M_vs_F                    -1.875      1.315  -1.426 0.161382    
## alcohol.Non_vs_P                 -2.708      0.930  -2.912 0.005727 ** 
## alcohol.P2_vs_P4                 -9.062      1.611  -5.626 1.37e-06 ***
## gender.M_vs_F:alcohol.Non_vs_P   -2.500      0.930  -2.688 0.010258 *  
## gender.M_vs_F:alcohol.P2_vs_P4   -6.562      1.611  -4.074 0.000201 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.112 on 42 degrees of freedom
## Multiple R-squared:  0.6111, Adjusted R-squared:  0.5648 
## F-statistic:  13.2 on 5 and 42 DF,  p-value: 9.609e-08</code></pre>
<p>¿Qué vemos?
Primero. No hay un impacto del género (gender.M_vs_F).</p>
<p>Segundo. Parece que cualquier cantidad de alcohol afecta la percepción de atractivo cuando se compara con una condición sin alcohol (alcohol.Non_vs_P). Sin embargo, esto no es real. La comparación es significativa porque considera el efecto combinado de 2 y 4 pints, y las 4 pints tiene un efecto que arrastra el efecto total. De hecho si miramos el contraste de 2 versus 4 pints (alcohol.P2_vs_P4) vemos que hay un diferencia entre 2 y 4 pints. El promedio del grupo de 2 pints (64.69) es diferente del promedio del grupo de 4 pints (46.56). Esta diferencia es de -18.13 (46.56 - 64.69). El beta es este valor dividido por el número de grupos involucrados en el contraste (-18.13/2 = 9.06).</p>
<p>Tercero. En las interacciones (gender.M_vs_F:alcohol.Non_vs_P y gender.M_vs_F:alcohol.P2_vs_P4) se evalúan sí los efectos del consumo de alcohol son diferentes entre hombres y mujeres. Sabemos que esta interacción refleja que el efecto del consumo de alcohol depende del género. Al igual que en el punto anterior observamos que hay un diferencia entre consumir 4 pints y 2 pints, pero esto ocurre sólo para los hombres.</p>
</div>
<div id="anova-de-medidas-repetidas" class="section level2" number="10.3">
<h2><span class="header-section-number">10.3</span> ANOVA de medidas repetidas</h2>
<p>Ahora vamos a hacer un análisis un ANOVA de medidas repetidas. Primero seteamos nuestro directorio de trabajo y cargamos las librerías que necesitemos (si no las tienes instaladas debes instalarlas).</p>
<div class="sourceCode" id="cb485"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb485-1"><a href="más-allá-del-anova.html#cb485-1" tabindex="-1"></a><span class="fu">setwd</span>(<span class="fu">Sys.getenv</span>(<span class="st">&quot;BOOKDOWN_PROJECT_PATH&quot;</span>))</span>
<span id="cb485-2"><a href="más-allá-del-anova.html#cb485-2" tabindex="-1"></a></span>
<span id="cb485-3"><a href="más-allá-del-anova.html#cb485-3" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb485-4"><a href="más-allá-del-anova.html#cb485-4" tabindex="-1"></a><span class="fu">library</span>(Rmisc)</span>
<span id="cb485-5"><a href="más-allá-del-anova.html#cb485-5" tabindex="-1"></a><span class="fu">library</span>(pastecs)</span>
<span id="cb485-6"><a href="más-allá-del-anova.html#cb485-6" tabindex="-1"></a><span class="fu">library</span>(reshape)</span>
<span id="cb485-7"><a href="más-allá-del-anova.html#cb485-7" tabindex="-1"></a><span class="fu">library</span>(ez)</span>
<span id="cb485-8"><a href="más-allá-del-anova.html#cb485-8" tabindex="-1"></a><span class="fu">library</span>(multcomp)</span></code></pre></div>
<p>Primero importamos el set de datos y le damos una mirada.</p>
<div class="sourceCode" id="cb486"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb486-1"><a href="más-allá-del-anova.html#cb486-1" tabindex="-1"></a>dat1 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/insectos_y_tiempo_vomito.csv&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb486-2"><a href="más-allá-del-anova.html#cb486-2" tabindex="-1"></a><span class="fu">str</span>(dat1)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    8 obs. of  5 variables:
##  $ participante        : chr  &quot;P1&quot; &quot;P2&quot; &quot;P3&quot; &quot;P4&quot; ...
##  $ insecto.al.palo     : int  8 9 6 5 8 7 10 12
##  $ testiculo.de.canguro: int  7 5 2 3 4 5 2 6
##  $ ojos.de.pescado     : int  1 2 3 1 5 6 7 8
##  $ larvas.de.polillas  : int  6 5 8 9 8 7 2 1</code></pre>
<p>Enseguida transformamos los datos de formato wide a long y renombramos las columnas.</p>
<div class="sourceCode" id="cb488"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb488-1"><a href="más-allá-del-anova.html#cb488-1" tabindex="-1"></a>dat1.long <span class="ot">&lt;-</span> <span class="fu">melt</span>(dat1, </span>
<span id="cb488-2"><a href="más-allá-del-anova.html#cb488-2" tabindex="-1"></a>                 <span class="at">id =</span> <span class="st">&quot;participante&quot;</span>, </span>
<span id="cb488-3"><a href="más-allá-del-anova.html#cb488-3" tabindex="-1"></a>                 <span class="at">measured =</span> <span class="fu">c</span>(<span class="st">&quot;insecto.al.palo&quot;</span>, </span>
<span id="cb488-4"><a href="más-allá-del-anova.html#cb488-4" tabindex="-1"></a>                              <span class="st">&quot;testiculo.de.canguro&quot;</span>, </span>
<span id="cb488-5"><a href="más-allá-del-anova.html#cb488-5" tabindex="-1"></a>                              <span class="st">&quot;ojos.de.pescado&quot;</span>,</span>
<span id="cb488-6"><a href="más-allá-del-anova.html#cb488-6" tabindex="-1"></a>                              <span class="st">&quot;larvas.de.polillas&quot;</span>))</span>
<span id="cb488-7"><a href="más-allá-del-anova.html#cb488-7" tabindex="-1"></a><span class="fu">names</span>(dat1.long) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;participante&quot;</span>, <span class="st">&quot;animal&quot;</span>, <span class="st">&quot;vomito&quot;</span>)</span></code></pre></div>
<p>Antes de hacer cualquier análisis miramos los datos con un gráfico.
Usamos la función <strong>summarySEwithin</strong> para calcular los estadísticos.</p>
<div class="sourceCode" id="cb489"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb489-1"><a href="más-allá-del-anova.html#cb489-1" tabindex="-1"></a>datac <span class="ot">&lt;-</span> <span class="fu">summarySEwithin</span>(dat1.long, </span>
<span id="cb489-2"><a href="más-allá-del-anova.html#cb489-2" tabindex="-1"></a>                         <span class="at">measurevar=</span><span class="st">&quot;vomito&quot;</span>, </span>
<span id="cb489-3"><a href="más-allá-del-anova.html#cb489-3" tabindex="-1"></a>                         <span class="at">withinvars=</span><span class="st">&quot;animal&quot;</span>, </span>
<span id="cb489-4"><a href="más-allá-del-anova.html#cb489-4" tabindex="-1"></a>                         <span class="at">idvar=</span><span class="st">&quot;participante&quot;</span>)</span></code></pre></div>
<p>Luego hacemos el gráfico.</p>
<div class="sourceCode" id="cb490"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb490-1"><a href="más-allá-del-anova.html#cb490-1" tabindex="-1"></a><span class="fu">ggplot</span>(datac, <span class="fu">aes</span>(<span class="at">x=</span>animal, <span class="at">y=</span>vomito, <span class="at">group=</span><span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb490-2"><a href="más-allá-del-anova.html#cb490-2" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="at">width=</span>.<span class="dv">1</span>, <span class="fu">aes</span>(<span class="at">ymin=</span>vomito<span class="sc">-</span>se, <span class="at">ymax=</span>vomito<span class="sc">+</span>se)) <span class="sc">+</span></span>
<span id="cb490-3"><a href="más-allá-del-anova.html#cb490-3" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">colour =</span> <span class="st">&quot;Red&quot;</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>) <span class="sc">+</span> </span>
<span id="cb490-4"><a href="más-allá-del-anova.html#cb490-4" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb490-5"><a href="más-allá-del-anova.html#cb490-5" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Tiempo para vomitar (segundos)&quot;</span>) <span class="sc">+</span></span>
<span id="cb490-6"><a href="más-allá-del-anova.html#cb490-6" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Tipo de comida&quot;</span>) <span class="sc">+</span></span>
<span id="cb490-7"><a href="más-allá-del-anova.html#cb490-7" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(), <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb490-8"><a href="más-allá-del-anova.html#cb490-8" tabindex="-1"></a>        <span class="at">panel.background =</span> <span class="fu">element_blank</span>(), <span class="at">axis.line =</span> <span class="fu">element_line</span>(<span class="at">colour =</span> <span class="st">&quot;black&quot;</span>))</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-244-1.png" width="672" /></p>
<p>Luego podemos tener una descripción de los datos.</p>
<div class="sourceCode" id="cb491"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb491-1"><a href="más-allá-del-anova.html#cb491-1" tabindex="-1"></a>test <span class="ot">&lt;-</span> <span class="fu">by</span>(dat1.long<span class="sc">$</span>vomito, </span>
<span id="cb491-2"><a href="más-allá-del-anova.html#cb491-2" tabindex="-1"></a>           dat1.long<span class="sc">$</span>animal, </span>
<span id="cb491-3"><a href="más-allá-del-anova.html#cb491-3" tabindex="-1"></a>           stat.desc, </span>
<span id="cb491-4"><a href="más-allá-del-anova.html#cb491-4" tabindex="-1"></a>           <span class="at">basic =</span> <span class="cn">FALSE</span>, </span>
<span id="cb491-5"><a href="más-allá-del-anova.html#cb491-5" tabindex="-1"></a>           <span class="at">norm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb491-6"><a href="más-allá-del-anova.html#cb491-6" tabindex="-1"></a><span class="fu">lapply</span>(test,round,<span class="dv">2</span>)</span></code></pre></div>
<pre><code>## $insecto.al.palo
##       median         mean      SE.mean CI.mean.0.95          var      std.dev     coef.var     skewness     skew.2SE 
##         8.00         8.12         0.79         1.87         4.98         2.23         0.27         0.27         0.18 
##     kurtosis     kurt.2SE   normtest.W   normtest.p 
##        -1.21        -0.41         0.98         0.97 
## 
## $testiculo.de.canguro
##       median         mean      SE.mean CI.mean.0.95          var      std.dev     coef.var     skewness     skew.2SE 
##         4.50         4.25         0.65         1.53         3.36         1.83         0.43         0.05         0.03 
##     kurtosis     kurt.2SE   normtest.W   normtest.p 
##        -1.66        -0.56         0.94         0.60 
## 
## $ojos.de.pescado
##       median         mean      SE.mean CI.mean.0.95          var      std.dev     coef.var     skewness     skew.2SE 
##         4.00         4.12         0.97         2.30         7.55         2.75         0.67         0.10         0.07 
##     kurtosis     kurt.2SE   normtest.W   normtest.p 
##        -1.86        -0.63         0.91         0.37 
## 
## $larvas.de.polillas
##       median         mean      SE.mean CI.mean.0.95          var      std.dev     coef.var     skewness     skew.2SE 
##         6.50         5.75         1.03         2.44         8.50         2.92         0.51        -0.51        -0.34 
##     kurtosis     kurt.2SE   normtest.W   normtest.p 
##        -1.49        -0.50         0.90         0.29</code></pre>
<p>Finalmente, hacemos el análisis de ANOVA de medidas repetidas.</p>
<div class="sourceCode" id="cb493"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb493-1"><a href="más-allá-del-anova.html#cb493-1" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">ezANOVA</span>(<span class="at">data =</span> dat1.long,</span>
<span id="cb493-2"><a href="más-allá-del-anova.html#cb493-2" tabindex="-1"></a>                 <span class="at">dv =</span> .(vomito),</span>
<span id="cb493-3"><a href="más-allá-del-anova.html#cb493-3" tabindex="-1"></a>                 <span class="at">wid =</span> .(participante),</span>
<span id="cb493-4"><a href="más-allá-del-anova.html#cb493-4" tabindex="-1"></a>                 <span class="at">within =</span> .(animal),</span>
<span id="cb493-5"><a href="más-allá-del-anova.html#cb493-5" tabindex="-1"></a>                 <span class="at">type =</span> <span class="dv">3</span>,</span>
<span id="cb493-6"><a href="más-allá-del-anova.html#cb493-6" tabindex="-1"></a>                 <span class="at">detailed =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Warning: Converting &quot;participante&quot; to factor for ANOVA.</code></pre>
<div class="sourceCode" id="cb495"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb495-1"><a href="más-allá-del-anova.html#cb495-1" tabindex="-1"></a>model</span></code></pre></div>
<pre><code>## $ANOVA
##        Effect DFn DFd     SSn     SSd          F            p p&lt;.05       ges
## 1 (Intercept)   1   7 990.125  17.375 398.899281 1.973536e-07     * 0.8529127
## 2      animal   3  21  83.125 153.375   3.793806 2.557030e-02     * 0.3274249
## 
## $`Mauchly&#39;s Test for Sphericity`
##   Effect        W          p p&lt;.05
## 2 animal 0.136248 0.04684581     *
## 
## $`Sphericity Corrections`
##   Effect       GGe      p[GG] p[GG]&lt;.05       HFe      p[HF] p[HF]&lt;.05
## 2 animal 0.5328456 0.06258412           0.6657636 0.04833061         *</code></pre>
<p>¿Qué observamos?
El modelo sugiere que hay un efecto del tipo de animal sobre el número de vómitos.
Sin embargo, el test de Mauchly nos dice que no se cumple el supuesto de esfericidad.
Por lo tanto debemos mirar las correcciones (Greenhouse-Geisser [GG] o Huynd-Feldt [HF]).</p>
<p>Luego del análisis de ANOVA podemos evaluar que comparaciones son significativamente diferentes.</p>
<div class="sourceCode" id="cb497"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb497-1"><a href="más-allá-del-anova.html#cb497-1" tabindex="-1"></a><span class="fu">pairwise.t.test</span>(dat1.long<span class="sc">$</span>vomito, </span>
<span id="cb497-2"><a href="más-allá-del-anova.html#cb497-2" tabindex="-1"></a>                dat1.long<span class="sc">$</span>animal,</span>
<span id="cb497-3"><a href="más-allá-del-anova.html#cb497-3" tabindex="-1"></a>                <span class="at">paired =</span> <span class="cn">TRUE</span>, </span>
<span id="cb497-4"><a href="más-allá-del-anova.html#cb497-4" tabindex="-1"></a>                <span class="at">p.adjust.method =</span> <span class="st">&quot;bonferroni&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Pairwise comparisons using paired t tests 
## 
## data:  dat1.long$vomito and dat1.long$animal 
## 
##                      insecto.al.palo testiculo.de.canguro ojos.de.pescado
## testiculo.de.canguro 0.0121          -                    -              
## ojos.de.pescado      0.0056          1.0000               -              
## larvas.de.polillas   1.0000          1.0000               1.0000         
## 
## P value adjustment method: bonferroni</code></pre>
<p>Finalmente, también puedes notar que el modelo de ANOVA también describe el tamaño del efecto en forma de ges (generalized eta squared).</p>
</div>
<div id="ancova" class="section level2" number="10.4">
<h2><span class="header-section-number">10.4</span> ANCOVA</h2>
<p>Ahora vamos a hacer un análisis un ANCOVA.
Imagina que estuvimos estudiando el efecto de una droga sobre los niveles de inteligencia de unos individuos (revisa el capítulo sobre ANOVA).</p>
<div class="sourceCode" id="cb499"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb499-1"><a href="más-allá-del-anova.html#cb499-1" tabindex="-1"></a><span class="fu">setwd</span>(<span class="fu">Sys.getenv</span>(<span class="st">&quot;BOOKDOWN_PROJECT_PATH&quot;</span>))</span>
<span id="cb499-2"><a href="más-allá-del-anova.html#cb499-2" tabindex="-1"></a></span>
<span id="cb499-3"><a href="más-allá-del-anova.html#cb499-3" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb499-4"><a href="más-allá-del-anova.html#cb499-4" tabindex="-1"></a><span class="fu">library</span>(Hmisc)</span>
<span id="cb499-5"><a href="más-allá-del-anova.html#cb499-5" tabindex="-1"></a><span class="fu">library</span>(Rmisc)</span>
<span id="cb499-6"><a href="más-allá-del-anova.html#cb499-6" tabindex="-1"></a><span class="fu">library</span>(effsize)</span>
<span id="cb499-7"><a href="más-allá-del-anova.html#cb499-7" tabindex="-1"></a><span class="fu">library</span>(pastecs)</span>
<span id="cb499-8"><a href="más-allá-del-anova.html#cb499-8" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span>
<span id="cb499-9"><a href="más-allá-del-anova.html#cb499-9" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb499-10"><a href="más-allá-del-anova.html#cb499-10" tabindex="-1"></a><span class="fu">library</span>(effsize)</span>
<span id="cb499-11"><a href="más-allá-del-anova.html#cb499-11" tabindex="-1"></a><span class="fu">library</span>(effects)</span>
<span id="cb499-12"><a href="más-allá-del-anova.html#cb499-12" tabindex="-1"></a><span class="fu">library</span>(multcomp)</span></code></pre></div>
<div class="sourceCode" id="cb500"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb500-1"><a href="más-allá-del-anova.html#cb500-1" tabindex="-1"></a>dat1 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/inteligencia.csv&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb500-2"><a href="más-allá-del-anova.html#cb500-2" tabindex="-1"></a>dat1<span class="sc">$</span>Dosis <span class="ot">&lt;-</span> <span class="fu">factor</span>(dat1<span class="sc">$</span>Dosis, </span>
<span id="cb500-3"><a href="más-allá-del-anova.html#cb500-3" tabindex="-1"></a>                            <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Placebo&quot;</span>, <span class="st">&quot;Baja&quot;</span>, <span class="st">&quot;Alta&quot;</span>))</span>
<span id="cb500-4"><a href="más-allá-del-anova.html#cb500-4" tabindex="-1"></a>dat1</span></code></pre></div>
<pre><code>##      Dosis Inteligencia
## 1  Placebo            3
## 2  Placebo            2
## 3  Placebo            1
## 4  Placebo            1
## 5  Placebo            4
## 6     Baja            5
## 7     Baja            2
## 8     Baja            4
## 9     Baja            2
## 10    Baja            3
## 11    Alta            7
## 12    Alta            4
## 13    Alta            5
## 14    Alta            3
## 15    Alta            6</code></pre>
<div class="sourceCode" id="cb502"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb502-1"><a href="más-allá-del-anova.html#cb502-1" tabindex="-1"></a><span class="co"># Podemos usar esta función para calcular los estadísticos a través de los participantes.</span></span>
<span id="cb502-2"><a href="más-allá-del-anova.html#cb502-2" tabindex="-1"></a>datac <span class="ot">&lt;-</span> <span class="fu">summarySE</span>(dat1, </span>
<span id="cb502-3"><a href="más-allá-del-anova.html#cb502-3" tabindex="-1"></a>                   <span class="at">measurevar=</span><span class="st">&quot;Inteligencia&quot;</span>, </span>
<span id="cb502-4"><a href="más-allá-del-anova.html#cb502-4" tabindex="-1"></a>                   <span class="at">groupvars=</span><span class="st">&quot;Dosis&quot;</span>)</span>
<span id="cb502-5"><a href="más-allá-del-anova.html#cb502-5" tabindex="-1"></a></span>
<span id="cb502-6"><a href="más-allá-del-anova.html#cb502-6" tabindex="-1"></a><span class="co"># Luego hacemos el gráfico</span></span>
<span id="cb502-7"><a href="más-allá-del-anova.html#cb502-7" tabindex="-1"></a><span class="fu">ggplot</span>(datac, <span class="fu">aes</span>(<span class="at">x=</span>Dosis, <span class="at">y=</span>Inteligencia, <span class="at">group=</span><span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb502-8"><a href="más-allá-del-anova.html#cb502-8" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="at">width=</span>.<span class="dv">1</span>, <span class="fu">aes</span>(<span class="at">ymin=</span>Inteligencia<span class="sc">-</span>se, <span class="at">ymax=</span>Inteligencia<span class="sc">+</span>se)) <span class="sc">+</span></span>
<span id="cb502-9"><a href="más-allá-del-anova.html#cb502-9" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">colour =</span> <span class="st">&quot;Red&quot;</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>) <span class="sc">+</span> </span>
<span id="cb502-10"><a href="más-allá-del-anova.html#cb502-10" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb502-11"><a href="más-allá-del-anova.html#cb502-11" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Niveles de inteligencia&quot;</span>) <span class="sc">+</span></span>
<span id="cb502-12"><a href="más-allá-del-anova.html#cb502-12" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(), <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb502-13"><a href="más-allá-del-anova.html#cb502-13" tabindex="-1"></a>        <span class="at">panel.background =</span> <span class="fu">element_blank</span>(), <span class="at">axis.line =</span> <span class="fu">element_line</span>(<span class="at">colour =</span> <span class="st">&quot;black&quot;</span>))</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-249-1.png" width="672" /></p>
<p>Para el análisis de ANOVA observamos lo siguiente.</p>
<div class="sourceCode" id="cb503"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb503-1"><a href="más-allá-del-anova.html#cb503-1" tabindex="-1"></a>m_AOV <span class="ot">&lt;-</span> <span class="fu">aov</span>(Inteligencia <span class="sc">~</span> Dosis, <span class="at">data =</span> dat1)</span>
<span id="cb503-2"><a href="más-allá-del-anova.html#cb503-2" tabindex="-1"></a><span class="fu">summary</span>(m_AOV)</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)  
## Dosis        2  20.13  10.067   5.119 0.0247 *
## Residuals   12  23.60   1.967                 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Según este análisis la droga tiene un efecto en los niveles de inteligencia.
Pero ¿qué pasa si tomamos en cuenta otros factores? Por ejemplo, qué pasa si tomamos en cuenta la edad de los participantes o los niveles de inteligencia de sus padres? Las variables continuas que no son parte de una manipulación experimental pero que tienen una influencia en la variable dependiente, se conocen como co-variables y se pueden incluir en un análisis de ANOVA. Cuándo medimos las co-variables y las incluimos en un análisis de varianza lo llamamos análisis de covarianza (o ANCOVA).</p>
<p>En el siguiente ejemplo vamos a analizar el efecto de la droga sobre los niveles de inteligencia considerando además los niveles de inteligencia de uno de sus progenitores.</p>
<p>Primero seteamos nuestro directorio de trabajo y cargamos las librerías que necesitemos (si no las tienes instaladas debes instalarlas).</p>
<div class="sourceCode" id="cb505"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb505-1"><a href="más-allá-del-anova.html#cb505-1" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb505-2"><a href="más-allá-del-anova.html#cb505-2" tabindex="-1"></a>dat2 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/inteligencia_y_covariable.csv&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb505-3"><a href="más-allá-del-anova.html#cb505-3" tabindex="-1"></a>dat2<span class="sc">$</span>dosis <span class="ot">&lt;-</span> <span class="fu">factor</span>(dat2<span class="sc">$</span>dosis,</span>
<span id="cb505-4"><a href="más-allá-del-anova.html#cb505-4" tabindex="-1"></a>                   <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>),</span>
<span id="cb505-5"><a href="más-allá-del-anova.html#cb505-5" tabindex="-1"></a>                   <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Placebo&quot;</span>,</span>
<span id="cb505-6"><a href="más-allá-del-anova.html#cb505-6" tabindex="-1"></a>                              <span class="st">&quot;Low Dose&quot;</span>,</span>
<span id="cb505-7"><a href="más-allá-del-anova.html#cb505-7" tabindex="-1"></a>                              <span class="st">&quot;High Dose&quot;</span>))</span></code></pre></div>
<p>Luego, pasamos los datos a formato long.</p>
<div class="sourceCode" id="cb506"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb506-1"><a href="más-allá-del-anova.html#cb506-1" tabindex="-1"></a>restructuredData <span class="ot">&lt;-</span> <span class="fu">melt</span>(dat2,</span>
<span id="cb506-2"><a href="más-allá-del-anova.html#cb506-2" tabindex="-1"></a>                         <span class="at">id =</span> <span class="fu">c</span>(<span class="st">&quot;dosis&quot;</span>),</span>
<span id="cb506-3"><a href="más-allá-del-anova.html#cb506-3" tabindex="-1"></a>                         <span class="at">measured =</span> <span class="fu">c</span>(<span class="st">&quot;inteligencia&quot;</span>, <span class="st">&quot;herencia&quot;</span>))</span>
<span id="cb506-4"><a href="más-allá-del-anova.html#cb506-4" tabindex="-1"></a><span class="fu">colnames</span>(restructuredData) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;dosis&quot;</span>, <span class="st">&quot;aspecto&quot;</span>, <span class="st">&quot;valor&quot;</span>)</span></code></pre></div>
<p>Luego, podemos hacer algunos gráficos.
Por ejemplo, podemos visualizar los niveles de inteligencia en función de la dosis de droga. Al mismo podemos ver como que diferencias hay los niveles de inteligencia heredados.</p>
<div class="sourceCode" id="cb507"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb507-1"><a href="más-allá-del-anova.html#cb507-1" tabindex="-1"></a><span class="fu">ggplot</span>(restructuredData, <span class="fu">aes</span>(dosis, valor)) <span class="sc">+</span></span>
<span id="cb507-2"><a href="más-allá-del-anova.html#cb507-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb507-3"><a href="más-allá-del-anova.html#cb507-3" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>aspecto) <span class="sc">+</span></span>
<span id="cb507-4"><a href="más-allá-del-anova.html#cb507-4" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">&quot;Dosis&quot;</span>, <span class="at">y =</span><span class="st">&quot;Inteligencia&quot;</span>) <span class="sc">+</span></span>
<span id="cb507-5"><a href="más-allá-del-anova.html#cb507-5" tabindex="-1"></a>     <span class="fu">theme</span>(<span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(), <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb507-6"><a href="más-allá-del-anova.html#cb507-6" tabindex="-1"></a>        <span class="at">panel.background =</span> <span class="fu">element_blank</span>(), <span class="at">axis.line =</span> <span class="fu">element_line</span>(<span class="at">colour =</span> <span class="st">&quot;black&quot;</span>))</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-253-1.png" width="672" /></p>
<p>Podemos observar cómo cambian los niveles de inteligencia individual en función de los niveles de inteligencia de los progenitores. Y podemos ver como cambia estos para los distintos niveles de droga.</p>
<div class="sourceCode" id="cb508"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb508-1"><a href="más-allá-del-anova.html#cb508-1" tabindex="-1"></a><span class="fu">ggplot</span>(dat2, <span class="fu">aes</span>(herencia, inteligencia, <span class="at">colour =</span> dosis)) <span class="sc">+</span></span>
<span id="cb508-2"><a href="más-allá-del-anova.html#cb508-2" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb508-3"><a href="más-allá-del-anova.html#cb508-3" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>) <span class="sc">+</span></span>
<span id="cb508-4"><a href="más-allá-del-anova.html#cb508-4" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">&quot;Inteligencia heredada&quot;</span>, <span class="at">y =</span><span class="st">&quot;Inteligencia evocada por la droga&quot;</span>) <span class="sc">+</span> </span>
<span id="cb508-5"><a href="más-allá-del-anova.html#cb508-5" tabindex="-1"></a>   <span class="fu">theme</span>(<span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(), <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb508-6"><a href="más-allá-del-anova.html#cb508-6" tabindex="-1"></a>        <span class="at">panel.background =</span> <span class="fu">element_blank</span>(), <span class="at">axis.line =</span> <span class="fu">element_line</span>(<span class="at">colour =</span> <span class="st">&quot;black&quot;</span>))</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-254-1.png" width="672" /></p>
<p>En seguida podemos hacer una descripción de los datos.</p>
<div class="sourceCode" id="cb510"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb510-1"><a href="más-allá-del-anova.html#cb510-1" tabindex="-1"></a><span class="fu">as.data.frame</span>(<span class="fu">lapply</span>(<span class="fu">by</span>(dat2<span class="sc">$</span>inteligencia, </span>
<span id="cb510-2"><a href="más-allá-del-anova.html#cb510-2" tabindex="-1"></a>                        dat2<span class="sc">$</span>dosis,</span>
<span id="cb510-3"><a href="más-allá-del-anova.html#cb510-3" tabindex="-1"></a>                        stat.desc, </span>
<span id="cb510-4"><a href="más-allá-del-anova.html#cb510-4" tabindex="-1"></a>                        <span class="at">basic =</span> <span class="cn">FALSE</span>, </span>
<span id="cb510-5"><a href="más-allá-del-anova.html#cb510-5" tabindex="-1"></a>                        <span class="at">norm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb510-6"><a href="más-allá-del-anova.html#cb510-6" tabindex="-1"></a>                     round, <span class="dv">2</span>))</span></code></pre></div>
<pre><code>##              Placebo Low.Dose High.Dose
## median          2.00     4.50      4.00
## mean            3.22     4.88      4.85
## SE.mean         0.60     0.52      0.59
## CI.mean.0.95    1.37     1.22      1.28
## var             3.19     2.12      4.47
## std.dev         1.79     1.46      2.12
## coef.var        0.55     0.30      0.44
## skewness        0.99     0.43      0.43
## skew.2SE        0.69     0.28      0.35
## kurtosis       -0.55    -1.48     -0.90
## kurt.2SE       -0.20    -0.50     -0.38
## normtest.W      0.76     0.87      0.93
## normtest.p      0.01     0.16      0.39</code></pre>
<div class="sourceCode" id="cb512"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb512-1"><a href="más-allá-del-anova.html#cb512-1" tabindex="-1"></a><span class="fu">as.data.frame</span>(<span class="fu">lapply</span>(<span class="fu">by</span>(dat2<span class="sc">$</span>herencia,</span>
<span id="cb512-2"><a href="más-allá-del-anova.html#cb512-2" tabindex="-1"></a>                        dat2<span class="sc">$</span>dosis,</span>
<span id="cb512-3"><a href="más-allá-del-anova.html#cb512-3" tabindex="-1"></a>                        stat.desc, </span>
<span id="cb512-4"><a href="más-allá-del-anova.html#cb512-4" tabindex="-1"></a>                        <span class="at">basic =</span> <span class="cn">FALSE</span>, </span>
<span id="cb512-5"><a href="más-allá-del-anova.html#cb512-5" tabindex="-1"></a>                        <span class="at">norm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb512-6"><a href="más-allá-del-anova.html#cb512-6" tabindex="-1"></a>                     round, <span class="dv">2</span>))</span></code></pre></div>
<pre><code>##              Placebo Low.Dose High.Dose
## median          4.00     2.50      2.00
## mean            3.44     3.12      2.00
## SE.mean         0.69     0.61      0.45
## CI.mean.0.95    1.59     1.44      0.99
## var             4.28     2.98      2.67
## std.dev         2.07     1.73      1.63
## coef.var        0.60     0.55      0.82
## skewness        0.22     0.42      0.21
## skew.2SE        0.15     0.28      0.17
## kurtosis       -1.47    -1.50     -1.36
## kurt.2SE       -0.53    -0.51     -0.57
## normtest.W      0.92     0.92      0.91
## normtest.p      0.40     0.42      0.20</code></pre>
<p>Podemos ver el gran promedio de inteligencia evocada por la droga (a travaés de todas las dosis).</p>
<div class="sourceCode" id="cb514"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb514-1"><a href="más-allá-del-anova.html#cb514-1" tabindex="-1"></a><span class="fu">as.data.frame</span>(<span class="fu">lapply</span>(<span class="fu">stat.desc</span>(dat2<span class="sc">$</span>inteligencia,</span>
<span id="cb514-2"><a href="más-allá-del-anova.html#cb514-2" tabindex="-1"></a>                               <span class="at">basic =</span> <span class="cn">FALSE</span>), </span>
<span id="cb514-3"><a href="más-allá-del-anova.html#cb514-3" tabindex="-1"></a>                     round, <span class="dv">2</span>))</span></code></pre></div>
<pre><code>##   median mean SE.mean CI.mean.0.95  var std.dev coef.var
## 1      4 4.37    0.36         0.73 3.83    1.96     0.45</code></pre>
<p>Podemos ver el gran promedio de inteligencia heredada (a travaés de todas las dosis).</p>
<div class="sourceCode" id="cb516"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb516-1"><a href="más-allá-del-anova.html#cb516-1" tabindex="-1"></a><span class="fu">as.data.frame</span>(<span class="fu">lapply</span>(<span class="fu">stat.desc</span>(dat2<span class="sc">$</span>herencia,</span>
<span id="cb516-2"><a href="más-allá-del-anova.html#cb516-2" tabindex="-1"></a>                               <span class="at">basic =</span> <span class="cn">FALSE</span>), </span>
<span id="cb516-3"><a href="más-allá-del-anova.html#cb516-3" tabindex="-1"></a>                     round, <span class="dv">2</span>))</span></code></pre></div>
<pre><code>##   median mean SE.mean CI.mean.0.95  var std.dev coef.var
## 1    2.5 2.73    0.34         0.69 3.44    1.86     0.68</code></pre>
<p>Luego podemos evaluar la homogeneidad de la varianza.</p>
<div class="sourceCode" id="cb518"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb518-1"><a href="más-allá-del-anova.html#cb518-1" tabindex="-1"></a><span class="fu">leveneTest</span>(dat2<span class="sc">$</span>inteligencia, dat2<span class="sc">$</span>dosis, <span class="at">center =</span> median)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  2  0.3256 0.7249
##       27</code></pre>
<p>Dentro de los supuestos del ANCOVA debemos probar que nuestra variable independiente y la co-variable producen efectos independientes. Es decir, debemos probar que la co-variable no es afectada por la variable independiente.</p>
<div class="sourceCode" id="cb520"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb520-1"><a href="más-allá-del-anova.html#cb520-1" tabindex="-1"></a>checkIndependenceModel <span class="ot">&lt;-</span> <span class="fu">aov</span>(herencia <span class="sc">~</span> dosis, <span class="at">data =</span> dat2)</span>
<span id="cb520-2"><a href="más-allá-del-anova.html#cb520-2" tabindex="-1"></a><span class="fu">summary</span>(checkIndependenceModel)</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)
## dosis        2  12.77   6.385   1.979  0.158
## Residuals   27  87.10   3.226</code></pre>
<div class="sourceCode" id="cb522"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb522-1"><a href="más-allá-del-anova.html#cb522-1" tabindex="-1"></a><span class="fu">summary.lm</span>(checkIndependenceModel)</span></code></pre></div>
<pre><code>## 
## Call:
## aov(formula = herencia ~ dosis, data = dat2)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.4444 -1.3646 -0.0625  1.0000  3.5556 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      3.4444     0.5987   5.753 4.06e-06 ***
## dosisLow Dose   -0.3194     0.8727  -0.366   0.7172    
## dosisHigh Dose  -1.4444     0.7788  -1.855   0.0746 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.796 on 27 degrees of freedom
## Multiple R-squared:  0.1279, Adjusted R-squared:  0.06326 
## F-statistic: 1.979 on 2 and 27 DF,  p-value: 0.1577</code></pre>
<p>La inteligencia heredada fue aproximadamente equivalente a través de las tres condiciones de drogas (placebo, dosis baja y alta). Este resultado nos permite decir que es apropiado utilizar la inteligencia heredada como co-variable en el análisis de ANCOVA.</p>
<p>El ANCOVA se realiza como cualquier modelo lineal. Es necesario mencionar que cuando hacemos un modelo, R calcula usa una suma de cuadrados de Tipo I (o sumas secuenciales de cuadrados) por defecto. Esto significa que cualquier predictor ingresado en el modelo se evalúa después de los predictores anteriores en el modelo. Típicamente en los modelos tradicionales se usa una suma de cuadrados de tipo III, dónde los efectos de los predictores se evalúan después que se toman en cuenta todos los otros predictores. Para hacer esto creamos el modelo y luego usamos la función <strong>Anova</strong> e indicamos que queremos usar la suma de cuadrados de tipo III.</p>
<div class="sourceCode" id="cb524"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb524-1"><a href="más-allá-del-anova.html#cb524-1" tabindex="-1"></a>ANCOVA_model <span class="ot">&lt;-</span> <span class="fu">aov</span>(inteligencia <span class="sc">~</span> herencia <span class="sc">+</span> dosis, dat2)</span>
<span id="cb524-2"><a href="más-allá-del-anova.html#cb524-2" tabindex="-1"></a><span class="fu">Anova</span>(ANCOVA_model, <span class="at">type=</span><span class="st">&quot;III&quot;</span>)</span></code></pre></div>
<pre><code>## Anova Table (Type III tests)
## 
## Response: inteligencia
##             Sum Sq Df F value  Pr(&gt;F)  
## (Intercept) 12.943  1  4.2572 0.04920 *
## herencia    15.076  1  4.9587 0.03483 *
## dosis       25.185  2  4.1419 0.02745 *
## Residuals   79.047 26                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>¿Cómo se interpretan estos resultados?
Lo primero que vemos es que los niveles de inteligencia individuales son modulados por los niveles de inteligencia de los progenitores. Más interesante aún es el segundo resultado, que indica que los niveles de inteligencia son modulados por la dosis de droga, incluso cuando los efectos de los niveles de inteligencia heredados son controlados.</p>
<p>En suma, si hubieramos hecho sólo el ANOVA hubieramos observado lo siguiente:</p>
<div class="sourceCode" id="cb526"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb526-1"><a href="más-allá-del-anova.html#cb526-1" tabindex="-1"></a>anovaModel <span class="ot">&lt;-</span> <span class="fu">aov</span>(inteligencia <span class="sc">~</span> dosis, dat2)</span>
<span id="cb526-2"><a href="más-allá-del-anova.html#cb526-2" tabindex="-1"></a><span class="fu">summary</span>(anovaModel)</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)
## dosis        2  16.84   8.422   2.416  0.108
## Residuals   27  94.12   3.486</code></pre>
<p>Pero, evaluando los niveles de inteligencia controlando por los niveles de inteligencia heredada llegamos a una conclusión distinta.</p>
<p>En el modelo de ANCOVA queda por mirar los gráficos.</p>
<div class="sourceCode" id="cb528"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb528-1"><a href="más-allá-del-anova.html#cb528-1" tabindex="-1"></a><span class="fu">plot</span>(ANCOVA_model)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-263-1.png" width="672" /><img src="bookdownproj_files/figure-html/unnamed-chunk-263-2.png" width="672" /><img src="bookdownproj_files/figure-html/unnamed-chunk-263-3.png" width="672" /><img src="bookdownproj_files/figure-html/unnamed-chunk-263-4.png" width="672" /></p>
<p>¿Qué vemos?
El primer gráfico se puede usar para evaluar la homogeneidad de la varianza: si tiene forma de embudo, entonces estamos en problemas. En nuestro caso vemos que la dispersión de puntajes es más amplia en algunos puntos que en otros. Esto implica que los residuales pueden estar distribuidos de forma heteroscedástica.</p>
<p>El segundo gráfico es un gráfico Q-Q que nos informa sobre la normalidad de los residuos en el modelo. Queremos que nuestros residuos se distribuyan normalmente, lo que significa que los puntos en el gráfico deben flotar alrededor de la línea diagonal. En nuestro los puntos se alejan de esta tendencia. Nuevamente, esta no es una buena noticia para el modelo. Estos gráficos sugieren que sería necesario realizar una versión robusta de ANCOVA.</p>
<p>A pesar de los problemas que hayamos detectado, y con el objetivo de hacer un análisis completo del análisis de ANCOVA veremos otros aspectos importantes.</p>
<p>Otro de los supuestos del ANCOVA que debemos probar es que existe una homogeneidad de las pendientes de regresión. Este supuesto significa que la relación entre la co-variable y la variable resultado (en este caso, inteligencia e inteligencia heredada) debe ser similar en diferentes niveles de la variable predictora (en este caso, en los tres grupos de dosis). Para probar esto, necesitamos ejecutar de nuevo un ANCOVA pero incluyendo la interacción entre la co-variable y la variable predictora.</p>
<div class="sourceCode" id="cb529"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb529-1"><a href="más-allá-del-anova.html#cb529-1" tabindex="-1"></a>hoRS <span class="ot">&lt;-</span> <span class="fu">aov</span>(inteligencia <span class="sc">~</span> herencia<span class="sc">*</span>dosis,</span>
<span id="cb529-2"><a href="más-allá-del-anova.html#cb529-2" tabindex="-1"></a>            dat2)</span>
<span id="cb529-3"><a href="más-allá-del-anova.html#cb529-3" tabindex="-1"></a><span class="fu">Anova</span>(hoRS, <span class="at">type =</span> <span class="st">&quot;III&quot;</span>)</span></code></pre></div>
<pre><code>## Anova Table (Type III tests)
## 
## Response: inteligencia
##                Sum Sq Df F value   Pr(&gt;F)   
## (Intercept)     0.771  1  0.3157 0.579405   
## herencia       19.922  1  8.1565 0.008715 **
## dosis          36.558  2  7.4836 0.002980 **
## herencia:dosis 20.427  2  4.1815 0.027667 * 
## Residuals      58.621 24                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Los efectos de la dosis de droga y la inteligencia heredada siguen siendo significativos, pero lo principal que nos interesa es la interacción. Un valor significativo en esta interacción sugiere que no cumple el supuesto de homogeneidad de las pendientes de regresión.</p>
<p>Para los contrastes planificados podemos hacer algo similar a lo que hemos hecho antes.</p>
<div class="sourceCode" id="cb531"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb531-1"><a href="más-allá-del-anova.html#cb531-1" tabindex="-1"></a>.plac_vs_drug <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb531-2"><a href="más-allá-del-anova.html#cb531-2" tabindex="-1"></a>.high_vs_low <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb531-3"><a href="más-allá-del-anova.html#cb531-3" tabindex="-1"></a><span class="fu">contrasts</span>(dat2<span class="sc">$</span>dosis) <span class="ot">&lt;-</span> <span class="fu">cbind</span>(.plac_vs_drug, .high_vs_low)</span></code></pre></div>
<p>Una vez que definimos los contrastes los podemos inyectar en la base de datos y luego realizamos el modelo nuevamente.</p>
<div class="sourceCode" id="cb532"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb532-1"><a href="más-allá-del-anova.html#cb532-1" tabindex="-1"></a>ANCOVA_model <span class="ot">&lt;-</span> <span class="fu">aov</span>(inteligencia <span class="sc">~</span> dosis <span class="sc">+</span> herencia, dat2)</span></code></pre></div>
<p>¿Cómo se interpretan estos resultados?
Antes de mirar las comparaciones planificadas es buena idea calcular los promedios ajustados. En este caso en particular queremos saber los promedios de inteligencia en función de las dosis de droga ajustados por los niveles de inteligencia heredados. Para ello usamos la función <strong>effect</strong>. También podemos acceder a los SE de estos promedios.</p>
<div class="sourceCode" id="cb533"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb533-1"><a href="más-allá-del-anova.html#cb533-1" tabindex="-1"></a>adjustedMeans <span class="ot">&lt;-</span> <span class="fu">effect</span>(<span class="st">&quot;dosis&quot;</span>, ANCOVA_model, <span class="at">se=</span><span class="cn">TRUE</span>)</span>
<span id="cb533-2"><a href="más-allá-del-anova.html#cb533-2" tabindex="-1"></a><span class="fu">summary</span>(adjustedMeans)</span></code></pre></div>
<pre><code>## 
##  dosis effect
## dosis
##   Placebo  Low Dose High Dose 
##  2.926370  4.712050  5.151251 
## 
##  Lower 95 Percent Confidence Limits
## dosis
##   Placebo  Low Dose High Dose 
##  1.700854  3.435984  4.118076 
## 
##  Upper 95 Percent Confidence Limits
## dosis
##   Placebo  Low Dose High Dose 
##  4.151886  5.988117  6.184427</code></pre>
<div class="sourceCode" id="cb535"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb535-1"><a href="más-allá-del-anova.html#cb535-1" tabindex="-1"></a>adjustedMeans<span class="sc">$</span>se</span></code></pre></div>
<pre><code>## [1] 0.5962045 0.6207971 0.5026323</code></pre>
<p>A diferencia de los promedios originales, cuando se ajustan los promedios se observa que los promedios de inteligencia para dosis alta y baja son bastante diferentes. Es decir, cuando se ajuste por los efectos de la inteligencia de los progenitores, a medida que aumenta la dosis de droga aumentan los niveles de inteligencia de los individuos.</p>
<p>Veamos los contrastes planificados.</p>
<div class="sourceCode" id="cb537"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb537-1"><a href="más-allá-del-anova.html#cb537-1" tabindex="-1"></a><span class="fu">summary.lm</span>(ANCOVA_model)</span></code></pre></div>
<pre><code>## 
## Call:
## aov(formula = inteligencia ~ dosis + herencia, data = dat2)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.2622 -0.7899 -0.3230  0.8811  4.5699 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)          3.1260     0.6250   5.002 3.34e-05 ***
## dosis.plac_vs_drug   0.6684     0.2400   2.785  0.00985 ** 
## dosis.high_vs_low    0.2196     0.4056   0.541  0.59284    
## herencia             0.4160     0.1868   2.227  0.03483 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.744 on 26 degrees of freedom
## Multiple R-squared:  0.2876, Adjusted R-squared:  0.2055 
## F-statistic:   3.5 on 3 and 26 DF,  p-value: 0.02954</code></pre>
<p>En estos contrastes comparamos el efecto de la droga relativo al placebo (contraste 1) y el efecto de la dosis alta versus la dosis baja (contraste 2). Pero, además estos contrates están ajustados por los niveles de inteligencia heredados. ¿Qué vemos? Primero, que hay un efecto de la droga por sobre el placebo. Segundo. No parece haber una efecto de la dosis alta por sobre la dosis baja.</p>
<p>El modelo además nos dice que hay una relación entre los niveles de inteligencia producidos por la droga y los niveles de inteligencia heredados. El beta es ~0.42. Asumiendo los otros factores en igualdad de condiciones, si la inteligencia del progenitor de un individuo aumenta en una 1 unidad, la inteligencia del individuo aumenta en alredor de la mitad. Esto los podemos ver en el siguiente gráfico.</p>
<div class="sourceCode" id="cb539"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb539-1"><a href="más-allá-del-anova.html#cb539-1" tabindex="-1"></a><span class="fu">ggplot</span>(dat2, <span class="fu">aes</span>(herencia, inteligencia)) <span class="sc">+</span></span>
<span id="cb539-2"><a href="más-allá-del-anova.html#cb539-2" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb539-3"><a href="más-allá-del-anova.html#cb539-3" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>) <span class="sc">+</span></span>
<span id="cb539-4"><a href="más-allá-del-anova.html#cb539-4" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">&quot;Inteligencia heredada&quot;</span>, <span class="at">y =</span><span class="st">&quot;Inteligencia evocada&quot;</span>) <span class="sc">+</span> </span>
<span id="cb539-5"><a href="más-allá-del-anova.html#cb539-5" tabindex="-1"></a>   <span class="fu">theme</span>(<span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(), <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb539-6"><a href="más-allá-del-anova.html#cb539-6" tabindex="-1"></a>        <span class="at">panel.background =</span> <span class="fu">element_blank</span>(), <span class="at">axis.line =</span> <span class="fu">element_line</span>(<span class="at">colour =</span> <span class="st">&quot;black&quot;</span>))</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-269-1.png" width="672" /></p>
<p>Por último, también podemos hacer pruebas posthoc. Para hacer estos análisis en los promedios ajustados debemos usar la función <strong>glht</strong>.</p>
<div class="sourceCode" id="cb541"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb541-1"><a href="más-allá-del-anova.html#cb541-1" tabindex="-1"></a>postHocs <span class="ot">&lt;-</span> <span class="fu">glht</span>(ANCOVA_model, <span class="at">linfct =</span> <span class="fu">mcp</span>(<span class="at">dosis =</span> <span class="st">&quot;Tukey&quot;</span>))</span>
<span id="cb541-2"><a href="más-allá-del-anova.html#cb541-2" tabindex="-1"></a><span class="fu">summary</span>(postHocs)</span></code></pre></div>
<pre><code>## 
##   Simultaneous Tests for General Linear Hypotheses
## 
## Multiple Comparisons of Means: Tukey Contrasts
## 
## 
## Fit: aov(formula = inteligencia ~ dosis + herencia, data = dat2)
## 
## Linear Hypotheses:
##                           Estimate Std. Error t value Pr(&gt;|t|)  
## Low Dose - Placebo == 0     1.7857     0.8494   2.102   0.1088  
## High Dose - Placebo == 0    2.2249     0.8028   2.771   0.0266 *
## High Dose - Low Dose == 0   0.4392     0.8112   0.541   0.8516  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## (Adjusted p values reported -- single-step method)</code></pre>
<div class="sourceCode" id="cb543"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb543-1"><a href="más-allá-del-anova.html#cb543-1" tabindex="-1"></a><span class="fu">confint</span>(postHocs)</span></code></pre></div>
<pre><code>## 
##   Simultaneous Confidence Intervals
## 
## Multiple Comparisons of Means: Tukey Contrasts
## 
## 
## Fit: aov(formula = inteligencia ~ dosis + herencia, data = dat2)
## 
## Quantile = 2.4868
## 95% family-wise confidence level
##  
## 
## Linear Hypotheses:
##                           Estimate lwr     upr    
## Low Dose - Placebo == 0    1.7857  -0.3265  3.8979
## High Dose - Placebo == 0   2.2249   0.2284  4.2213
## High Dose - Low Dose == 0  0.4392  -1.5782  2.4566</code></pre>
<p>De este análisis observamos que sólo hay diferencias de inteligencia (cuando controlamos por los efecto de inteligencia heredada) cuando comparamos el placebo y la dosis alta de droga.</p>
</div>
<div id="manova" class="section level2" number="10.5">
<h2><span class="header-section-number">10.5</span> MANOVA</h2>
<p>Ahora vamos a hacer un análisis de MANOVA.
El análisis de MANOVA se realizar porque el ANOVA lidia más que nada con una variable dependiente. Pero, ¿qué pasa cuando realizamos muchas mediciones?</p>
<p>En el siguiente estudio se aplicaron distintos tratamientos para enfrentar cierto tipo de problemas psicopatológicos. Había un grupo control (NT), y grupos a que se le aplicaron terapia condutual (BT) o terapia cognitivo-conductual (CBT). Además, de estos grupos (que reflejan las variables independientes), se midió la frecuencia de dos cosas: conductas y pensamientos.</p>
<p>Para empezar carguemos las librerías.</p>
<div class="sourceCode" id="cb545"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb545-1"><a href="más-allá-del-anova.html#cb545-1" tabindex="-1"></a><span class="fu">setwd</span>(<span class="fu">Sys.getenv</span>(<span class="st">&quot;BOOKDOWN_PROJECT_PATH&quot;</span>))</span>
<span id="cb545-2"><a href="más-allá-del-anova.html#cb545-2" tabindex="-1"></a></span>
<span id="cb545-3"><a href="más-allá-del-anova.html#cb545-3" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb545-4"><a href="más-allá-del-anova.html#cb545-4" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb545-5"><a href="más-allá-del-anova.html#cb545-5" tabindex="-1"></a><span class="fu">library</span>(mvnormtest)</span>
<span id="cb545-6"><a href="más-allá-del-anova.html#cb545-6" tabindex="-1"></a><span class="co">#library(mvoutlier)</span></span>
<span id="cb545-7"><a href="más-allá-del-anova.html#cb545-7" tabindex="-1"></a><span class="fu">library</span>(pastecs)</span>
<span id="cb545-8"><a href="más-allá-del-anova.html#cb545-8" tabindex="-1"></a><span class="fu">library</span>(reshape)</span>
<span id="cb545-9"><a href="más-allá-del-anova.html#cb545-9" tabindex="-1"></a><span class="co">#library(WRS)</span></span></code></pre></div>
<p>Carguemos los datos.</p>
<div class="sourceCode" id="cb546"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb546-1"><a href="más-allá-del-anova.html#cb546-1" tabindex="-1"></a>ocdData <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/OCD.csv&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb546-2"><a href="más-allá-del-anova.html#cb546-2" tabindex="-1"></a>ocdData<span class="sc">$</span>Grupo <span class="ot">&lt;-</span> <span class="fu">factor</span>(ocdData<span class="sc">$</span>Grupo,</span>
<span id="cb546-3"><a href="más-allá-del-anova.html#cb546-3" tabindex="-1"></a>                        <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;CBT&quot;</span>, <span class="st">&quot;BT&quot;</span>, <span class="st">&quot;No Treatment Control&quot;</span>),</span>
<span id="cb546-4"><a href="más-allá-del-anova.html#cb546-4" tabindex="-1"></a>                        <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;CBT&quot;</span>, <span class="st">&quot;BT&quot;</span>, <span class="st">&quot;NT&quot;</span>))</span></code></pre></div>
<p>Re-ordenemos los niveles dentro del factor de grupo para que en el gráfico aparezca el grupo control en primer lugar.</p>
<div class="sourceCode" id="cb547"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb547-1"><a href="más-allá-del-anova.html#cb547-1" tabindex="-1"></a>ocdData<span class="sc">$</span>Grupo <span class="ot">&lt;-</span> <span class="fu">factor</span>(ocdData<span class="sc">$</span>Grupo,</span>
<span id="cb547-2"><a href="más-allá-del-anova.html#cb547-2" tabindex="-1"></a>                        <span class="fu">levels</span>(ocdData<span class="sc">$</span>Grupo)[<span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">1</span>,<span class="dv">2</span>)])</span></code></pre></div>
<p>Luego transformemos los datos a formato Long-.</p>
<div class="sourceCode" id="cb548"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb548-1"><a href="más-allá-del-anova.html#cb548-1" tabindex="-1"></a>ocdMelt <span class="ot">&lt;-</span> <span class="fu">melt</span>(ocdData, </span>
<span id="cb548-2"><a href="más-allá-del-anova.html#cb548-2" tabindex="-1"></a>                <span class="at">id =</span> <span class="fu">c</span>(<span class="st">&quot;Grupo&quot;</span>),</span>
<span id="cb548-3"><a href="más-allá-del-anova.html#cb548-3" tabindex="-1"></a>                <span class="at">measured =</span> <span class="fu">c</span>(<span class="st">&quot;Acciones&quot;</span>, <span class="st">&quot;Pensamientos&quot;</span>))</span>
<span id="cb548-4"><a href="más-allá-del-anova.html#cb548-4" tabindex="-1"></a><span class="fu">names</span>(ocdMelt) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Grupo&quot;</span>, <span class="st">&quot;Medicion&quot;</span>, <span class="st">&quot;Frecuencia&quot;</span>)</span></code></pre></div>
<p>Hagamos un gráfico de dispersión.</p>
<div class="sourceCode" id="cb549"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb549-1"><a href="más-allá-del-anova.html#cb549-1" tabindex="-1"></a>ocdScatter <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(ocdData, <span class="fu">aes</span>(Acciones, Pensamientos))</span>
<span id="cb549-2"><a href="más-allá-del-anova.html#cb549-2" tabindex="-1"></a>ocdScatter <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>) <span class="sc">+</span></span>
<span id="cb549-3"><a href="más-allá-del-anova.html#cb549-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Conductas obsesivas&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Pensamientos obsesivos&quot;</span>) <span class="sc">+</span></span>
<span id="cb549-4"><a href="más-allá-del-anova.html#cb549-4" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Grupo, <span class="at">ncol =</span> <span class="dv">3</span>) <span class="sc">+</span> </span>
<span id="cb549-5"><a href="más-allá-del-anova.html#cb549-5" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(), <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb549-6"><a href="más-allá-del-anova.html#cb549-6" tabindex="-1"></a>        <span class="at">panel.background =</span> <span class="fu">element_blank</span>(), <span class="at">axis.line =</span> <span class="fu">element_line</span>(<span class="at">colour =</span> <span class="st">&quot;black&quot;</span>))</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-275-1.png" width="672" /></p>
<p>Hagamos un gráfico de barras.</p>
<div class="sourceCode" id="cb551"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb551-1"><a href="más-allá-del-anova.html#cb551-1" tabindex="-1"></a>ocdBar <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(ocdMelt, <span class="fu">aes</span>(Grupo, Frecuencia, <span class="at">fill =</span> Medicion))</span>
<span id="cb551-2"><a href="más-allá-del-anova.html#cb551-2" tabindex="-1"></a>ocdBar <span class="sc">+</span> </span>
<span id="cb551-3"><a href="más-allá-del-anova.html#cb551-3" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_cl_boot,</span>
<span id="cb551-4"><a href="más-allá-del-anova.html#cb551-4" tabindex="-1"></a>               <span class="at">geom =</span> <span class="st">&quot;errorbar&quot;</span>, </span>
<span id="cb551-5"><a href="más-allá-del-anova.html#cb551-5" tabindex="-1"></a>               <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width=</span><span class="fl">0.90</span>),</span>
<span id="cb551-6"><a href="más-allá-del-anova.html#cb551-6" tabindex="-1"></a>               <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb551-7"><a href="más-allá-del-anova.html#cb551-7" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.y =</span> mean, </span>
<span id="cb551-8"><a href="más-allá-del-anova.html#cb551-8" tabindex="-1"></a>               <span class="at">geom =</span> <span class="st">&quot;bar&quot;</span>, </span>
<span id="cb551-9"><a href="más-allá-del-anova.html#cb551-9" tabindex="-1"></a>               <span class="at">position =</span> <span class="st">&quot;dodge&quot;</span>) <span class="sc">+</span></span>
<span id="cb551-10"><a href="más-allá-del-anova.html#cb551-10" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Grupo&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Frencuencia&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;Medición&quot;</span>) <span class="sc">+</span> </span>
<span id="cb551-11"><a href="más-allá-del-anova.html#cb551-11" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">20</span>, <span class="at">by =</span> <span class="dv">2</span>)) <span class="sc">+</span> </span>
<span id="cb551-12"><a href="más-allá-del-anova.html#cb551-12" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(), <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb551-13"><a href="más-allá-del-anova.html#cb551-13" tabindex="-1"></a>        <span class="at">panel.background =</span> <span class="fu">element_blank</span>(), <span class="at">axis.line =</span> <span class="fu">element_line</span>(<span class="at">colour =</span> <span class="st">&quot;black&quot;</span>))</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-276-1.png" width="672" /></p>
<p>Hagamos un histograma.</p>
<div class="sourceCode" id="cb552"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb552-1"><a href="más-allá-del-anova.html#cb552-1" tabindex="-1"></a>ocdBoxplot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(ocdMelt, <span class="fu">aes</span>(Grupo, Frecuencia, <span class="at">colour =</span> Medicion))</span>
<span id="cb552-2"><a href="más-allá-del-anova.html#cb552-2" tabindex="-1"></a>ocdBoxplot <span class="sc">+</span> </span>
<span id="cb552-3"><a href="más-allá-del-anova.html#cb552-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> </span>
<span id="cb552-4"><a href="más-allá-del-anova.html#cb552-4" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Grupo&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Frecuencia&quot;</span>, <span class="at">colour =</span> <span class="st">&quot;Medición&quot;</span>) <span class="sc">+</span> </span>
<span id="cb552-5"><a href="más-allá-del-anova.html#cb552-5" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">20</span>, <span class="at">by =</span> <span class="dv">2</span>)) <span class="sc">+</span> </span>
<span id="cb552-6"><a href="más-allá-del-anova.html#cb552-6" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(), <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb552-7"><a href="más-allá-del-anova.html#cb552-7" tabindex="-1"></a>        <span class="at">panel.background =</span> <span class="fu">element_blank</span>(), <span class="at">axis.line =</span> <span class="fu">element_line</span>(<span class="at">colour =</span> <span class="st">&quot;black&quot;</span>))</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-277-1.png" width="672" /></p>
<p>Luego podemos hacer una descripción de los datos.</p>
<div class="sourceCode" id="cb553"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb553-1"><a href="más-allá-del-anova.html#cb553-1" tabindex="-1"></a>descrip <span class="ot">&lt;-</span> <span class="fu">by</span>(ocdData<span class="sc">$</span>Acciones, </span>
<span id="cb553-2"><a href="más-allá-del-anova.html#cb553-2" tabindex="-1"></a>           ocdData<span class="sc">$</span>Grupo, </span>
<span id="cb553-3"><a href="más-allá-del-anova.html#cb553-3" tabindex="-1"></a>           stat.desc, </span>
<span id="cb553-4"><a href="más-allá-del-anova.html#cb553-4" tabindex="-1"></a>           <span class="at">basic =</span> <span class="cn">FALSE</span>, </span>
<span id="cb553-5"><a href="más-allá-del-anova.html#cb553-5" tabindex="-1"></a>           <span class="at">norm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb553-6"><a href="más-allá-del-anova.html#cb553-6" tabindex="-1"></a><span class="fu">lapply</span>(descrip,round,<span class="dv">2</span>)</span></code></pre></div>
<pre><code>## $NT
##       median         mean      SE.mean CI.mean.0.95          var      std.dev     coef.var     skewness     skew.2SE 
##         5.00         5.00         0.33         0.75         1.11         1.05         0.21         0.51         0.37 
##     kurtosis     kurt.2SE   normtest.W   normtest.p 
##        -1.22        -0.46         0.86         0.07 
## 
## $CBT
##       median         mean      SE.mean CI.mean.0.95          var      std.dev     coef.var     skewness     skew.2SE 
##         5.00         4.90         0.38         0.86         1.43         1.20         0.24         0.17         0.12 
##     kurtosis     kurt.2SE   normtest.W   normtest.p 
##        -1.18        -0.44         0.95         0.69 
## 
## $BT
##       median         mean      SE.mean CI.mean.0.95          var      std.dev     coef.var     skewness     skew.2SE 
##         4.00         3.70         0.56         1.26         3.12         1.77         0.48        -0.46        -0.34 
##     kurtosis     kurt.2SE   normtest.W   normtest.p 
##        -1.45        -0.54         0.87         0.11</code></pre>
<div class="sourceCode" id="cb555"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb555-1"><a href="más-allá-del-anova.html#cb555-1" tabindex="-1"></a>descrip <span class="ot">&lt;-</span> <span class="fu">by</span>(ocdData<span class="sc">$</span>Pensamientos, </span>
<span id="cb555-2"><a href="más-allá-del-anova.html#cb555-2" tabindex="-1"></a>           ocdData<span class="sc">$</span>Grupo, </span>
<span id="cb555-3"><a href="más-allá-del-anova.html#cb555-3" tabindex="-1"></a>           stat.desc, </span>
<span id="cb555-4"><a href="más-allá-del-anova.html#cb555-4" tabindex="-1"></a>           <span class="at">basic =</span> <span class="cn">FALSE</span>, </span>
<span id="cb555-5"><a href="más-allá-del-anova.html#cb555-5" tabindex="-1"></a>           <span class="at">norm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb555-6"><a href="más-allá-del-anova.html#cb555-6" tabindex="-1"></a><span class="fu">lapply</span>(descrip,round,<span class="dv">2</span>)</span></code></pre></div>
<pre><code>## $NT
##       median         mean      SE.mean CI.mean.0.95          var      std.dev     coef.var     skewness     skew.2SE 
##        14.00        15.00         0.75         1.69         5.56         2.36         0.16         0.96         0.70 
##     kurtosis     kurt.2SE   normtest.W   normtest.p 
##        -0.54        -0.20         0.83         0.03 
## 
## $CBT
##       median         mean      SE.mean CI.mean.0.95          var      std.dev     coef.var     skewness     skew.2SE 
##        13.50        13.40         0.60         1.36         3.60         1.90         0.14         0.09         0.07 
##     kurtosis     kurt.2SE   normtest.W   normtest.p 
##        -1.67        -0.63         0.91         0.31 
## 
## $BT
##       median         mean      SE.mean CI.mean.0.95          var      std.dev     coef.var     skewness     skew.2SE 
##        14.50        15.20         0.66         1.50         4.40         2.10         0.14         0.61         0.44 
##     kurtosis     kurt.2SE   normtest.W   normtest.p 
##        -1.28        -0.48         0.88         0.12</code></pre>
<p>Luego de describir los datos podemos comprobar algunos supuestos antes de hacer el análisis de MANOVA.</p>
<p>Primero debemos chequear la homogeneidad de las matrices de covarianza, comparando los valores que encontremos. Idealmente deberían ser similares a través de los grupos.</p>
<div class="sourceCode" id="cb557"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb557-1"><a href="más-allá-del-anova.html#cb557-1" tabindex="-1"></a><span class="fu">by</span>(ocdData[, <span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>], ocdData<span class="sc">$</span>Grupo , cov)</span></code></pre></div>
<pre><code>## ocdData$Grupo: NT
##               Acciones Pensamientos
## Acciones      1.111111    -1.111111
## Pensamientos -1.111111     5.555556
## ----------------------------------------------------------------------------------------------- 
## ocdData$Grupo: CBT
##                Acciones Pensamientos
## Acciones     1.43333333   0.04444444
## Pensamientos 0.04444444   3.60000000
## ----------------------------------------------------------------------------------------------- 
## ocdData$Grupo: BT
##              Acciones Pensamientos
## Acciones     3.122222     2.511111
## Pensamientos 2.511111     4.400000</code></pre>
<p>En este caso se encuentran diferencias, pero ya que los grupos tienen un n similar no es algo de lo que tengamos que preocuparnos.</p>
<p>Luego tenemos que testear la normalidad multivariada. Para ello necesitamos aplicar una prueba de normalidada los grupos individuales, y transponer los datos para que estén en un formato adecuado.</p>
<div class="sourceCode" id="cb559"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb559-1"><a href="más-allá-del-anova.html#cb559-1" tabindex="-1"></a>nt <span class="ot">&lt;-</span> <span class="fu">t</span>(ocdData[<span class="dv">21</span><span class="sc">:</span><span class="dv">30</span>, <span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>])</span>
<span id="cb559-2"><a href="más-allá-del-anova.html#cb559-2" tabindex="-1"></a>cbt <span class="ot">&lt;-</span> <span class="fu">t</span>(ocdData[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>])</span>
<span id="cb559-3"><a href="más-allá-del-anova.html#cb559-3" tabindex="-1"></a>bt <span class="ot">&lt;-</span> <span class="fu">t</span>(ocdData[<span class="dv">11</span><span class="sc">:</span><span class="dv">20</span>, <span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>])</span>
<span id="cb559-4"><a href="más-allá-del-anova.html#cb559-4" tabindex="-1"></a></span>
<span id="cb559-5"><a href="más-allá-del-anova.html#cb559-5" tabindex="-1"></a><span class="fu">mshapiro.test</span>(nt)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  Z
## W = 0.82605, p-value = 0.02998</code></pre>
<div class="sourceCode" id="cb561"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb561-1"><a href="más-allá-del-anova.html#cb561-1" tabindex="-1"></a><span class="fu">mshapiro.test</span>(cbt)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  Z
## W = 0.9592, p-value = 0.7767</code></pre>
<div class="sourceCode" id="cb563"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb563-1"><a href="más-allá-del-anova.html#cb563-1" tabindex="-1"></a><span class="fu">mshapiro.test</span>(bt)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  Z
## W = 0.89122, p-value = 0.175</code></pre>
<p>El análisis sugiere que podrían haber problemas de normalidad en el grupo control. Por ahora lo vamos a ignorar. Pero mirando los datos se puede detectar un outlier. Y eliminando este outlier se puede realizar el análisis de normalidad para revisar si haciendo esto se corrige el problema de normalidad.</p>
<p>Antes de hacer el análisis principal podemos setear nuestros contrastes de interés.</p>
<div class="sourceCode" id="cb565"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb565-1"><a href="más-allá-del-anova.html#cb565-1" tabindex="-1"></a>.NT_vs_CBT <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb565-2"><a href="más-allá-del-anova.html#cb565-2" tabindex="-1"></a>.NT_vs_BT <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb565-3"><a href="más-allá-del-anova.html#cb565-3" tabindex="-1"></a><span class="fu">contrasts</span>(ocdData<span class="sc">$</span>Grupo) <span class="ot">&lt;-</span> <span class="fu">cbind</span>(.NT_vs_CBT, .NT_vs_BT)</span></code></pre></div>
<p>Luego para definir la variable dependiente creamos un vector con las dos mediciones.
Luego se realiza el modelo de la misma forma como se define en una regresión simple.
Finalmente revisamos el resultados del modelo.</p>
<div class="sourceCode" id="cb566"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb566-1"><a href="más-allá-del-anova.html#cb566-1" tabindex="-1"></a>outcome <span class="ot">&lt;-</span> <span class="fu">cbind</span>(ocdData<span class="sc">$</span>Acciones, ocdData<span class="sc">$</span>Pensamientos)</span>
<span id="cb566-2"><a href="más-allá-del-anova.html#cb566-2" tabindex="-1"></a>ocdModel <span class="ot">&lt;-</span> <span class="fu">manova</span>(outcome <span class="sc">~</span> Grupo, <span class="at">data =</span> ocdData)</span>
<span id="cb566-3"><a href="más-allá-del-anova.html#cb566-3" tabindex="-1"></a><span class="fu">summary</span>(ocdModel, <span class="at">intercept =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>##             Df  Pillai approx F num Df den Df  Pr(&gt;F)    
## (Intercept)  1 0.98285   745.23      2     26 &lt; 2e-16 ***
## Grupo        2 0.31845     2.56      4     54 0.04904 *  
## Residuals   27                                           
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Hay cuatro pruebas estadísticas que se pueden usar en MANOVA (traza de Pillai, lambda de Wilks, traza de Hotelling y prueba de raíz más grande de Roy). La prueba usada mas común es la traza de Pillai. Pero otras pruebas se pueden usar para condiciones particulares.</p>
<p>Otros análisis se pueden hacer de la siguiente manera:</p>
<div class="sourceCode" id="cb568"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb568-1"><a href="más-allá-del-anova.html#cb568-1" tabindex="-1"></a><span class="fu">summary</span>(ocdModel, <span class="at">intercept =</span> <span class="cn">TRUE</span>, <span class="at">test =</span> <span class="st">&quot;Wilks&quot;</span>)</span></code></pre></div>
<pre><code>##             Df   Wilks approx F num Df den Df  Pr(&gt;F)    
## (Intercept)  1 0.01715   745.23      2     26 &lt; 2e-16 ***
## Grupo        2 0.69851     2.55      4     52 0.04966 *  
## Residuals   27                                           
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb570"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb570-1"><a href="más-allá-del-anova.html#cb570-1" tabindex="-1"></a><span class="fu">summary</span>(ocdModel, <span class="at">intercept =</span> <span class="cn">TRUE</span>, <span class="at">test =</span> <span class="st">&quot;Hotelling&quot;</span>)</span></code></pre></div>
<pre><code>##             Df Hotelling-Lawley approx F num Df den Df Pr(&gt;F)    
## (Intercept)  1           57.325   745.23      2     26 &lt;2e-16 ***
## Grupo        2            0.407     2.55      4     50 0.0508 .  
## Residuals   27                                                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb572"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb572-1"><a href="más-allá-del-anova.html#cb572-1" tabindex="-1"></a><span class="fu">summary</span>(ocdModel, <span class="at">intercept =</span> <span class="cn">TRUE</span>, <span class="at">test =</span> <span class="st">&quot;Roy&quot;</span>)</span></code></pre></div>
<pre><code>##             Df    Roy approx F num Df den Df  Pr(&gt;F)    
## (Intercept)  1 57.325   745.23      2     26 &lt; 2e-16 ***
## Grupo        2  0.335     4.52      2     27 0.02027 *  
## Residuals   27                                          
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Finalmente luego de este análisis se pueden hacer análisis tipo ANOVA.
Se puede aplicar</p>
<div class="sourceCode" id="cb574"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb574-1"><a href="más-allá-del-anova.html#cb574-1" tabindex="-1"></a><span class="co"># Recuerda: outcome &lt;- cbind(ocdData$Acciones, ocdData$Pensamientos)</span></span>
<span id="cb574-2"><a href="más-allá-del-anova.html#cb574-2" tabindex="-1"></a><span class="fu">summary.aov</span>(ocdModel)</span></code></pre></div>
<pre><code>##  Response 1 :
##             Df Sum Sq Mean Sq F value  Pr(&gt;F)  
## Grupo        2 10.467  5.2333  2.7706 0.08046 .
## Residuals   27 51.000  1.8889                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##  Response 2 :
##             Df  Sum Sq Mean Sq F value Pr(&gt;F)
## Grupo        2  19.467  9.7333  2.1541 0.1355
## Residuals   27 122.000  4.5185</code></pre>
<p>Para los análisis de ANOVA observamos que no existen diferencias significativas entre los distintos tipos de terapia. Sólo con el fin de completar los análisis vamos a revisar las comparaciones planificadas. Pero no podemos intepretar estos resultados.</p>
<p>Se pueden analizar los cambios en la frecuencia de acciones en función de los tratamientos.</p>
<div class="sourceCode" id="cb576"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb576-1"><a href="más-allá-del-anova.html#cb576-1" tabindex="-1"></a>actionModel <span class="ot">&lt;-</span> <span class="fu">lm</span>(Acciones <span class="sc">~</span> Grupo, <span class="at">data =</span> ocdData)</span>
<span id="cb576-2"><a href="más-allá-del-anova.html#cb576-2" tabindex="-1"></a><span class="fu">summary.lm</span>(actionModel)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Acciones ~ Grupo, data = ocdData)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -2.700 -0.975  0.100  1.075  2.300 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       3.7000     0.4346   8.513 3.98e-09 ***
## Grupo.NT_vs_CBT   1.3000     0.6146   2.115   0.0438 *  
## Grupo.NT_vs_BT    1.2000     0.6146   1.952   0.0613 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.374 on 27 degrees of freedom
## Multiple R-squared:  0.1703, Adjusted R-squared:  0.1088 
## F-statistic: 2.771 on 2 and 27 DF,  p-value: 0.08046</code></pre>
<p>Se pueden analizar los cambios en la frecuencia de pensamientos en función de los tratamientos.</p>
<div class="sourceCode" id="cb578"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb578-1"><a href="más-allá-del-anova.html#cb578-1" tabindex="-1"></a>thoughtsModel <span class="ot">&lt;-</span> <span class="fu">lm</span>(Pensamientos <span class="sc">~</span> Grupo, <span class="at">data =</span> ocdData)</span>
<span id="cb578-2"><a href="más-allá-del-anova.html#cb578-2" tabindex="-1"></a><span class="fu">summary.lm</span>(thoughtsModel)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Pensamientos ~ Grupo, data = ocdData)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
##  -2.40  -1.40  -0.70   1.45   5.00 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      15.2000     0.6722  22.612   &lt;2e-16 ***
## Grupo.NT_vs_CBT  -0.2000     0.9506  -0.210   0.8349    
## Grupo.NT_vs_BT   -1.8000     0.9506  -1.893   0.0691 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.126 on 27 degrees of freedom
## Multiple R-squared:  0.1376, Adjusted R-squared:  0.07372 
## F-statistic: 2.154 on 2 and 27 DF,  p-value: 0.1355</code></pre>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="después-del-anova.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="otros-análisis.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/doctoradoenpsicologiautal/estadistica/edit/master/10_beyondANOVA.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/doctoradoenpsicologiautal/estadistica/blob/master/10_beyondANOVA.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
